---
- name: Install Headlamp
  ansible.builtin.command: >-
    {{ helm_binary }} upgrade --install headlamp headlamp/headlamp
    --version {{ helm_chart_lock.charts.headlamp.version }}
    --namespace headlamp --create-namespace
    --set service.type=LoadBalancer
    --set service.loadBalancerIP={{ headlamp_load_balancer_ip }}
    --wait --timeout 10m
  environment: "{{ helm_environment }}"
  when: install_headlamp
  changed_when: true
