all:
  vars:
    ansible_user: pi
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  children:
    k3s_cluster:
      children:
        k3s_servers:
          hosts:
            arm64-01:
              ansible_host: 192.168.2.51
            arm64-02:
              ansible_host: 192.168.2.52
            arm64-03:
              ansible_host: 192.168.2.53
        k3s_agents:
          hosts:
            arm64-04:
              ansible_host: 192.168.2.54
            arm64-05:
              ansible_host: 192.168.2.55
    minio_nodes:
      hosts:
        arm64-01:
        arm64-02:
        arm64-03:
        arm64-04:
        arm64-05:
