all:
  vars:
    ansible_user: dbuddenbaum
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
  children:
    microk8s_control_plane:
      hosts:
        arm64-01:
          ansible_host: 192.168.2.51
          node_labels:
            kubernetes.io/role: control-plane
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_ARM64_01_HDD
        arm64-02:
          ansible_host: 192.168.2.52
          node_labels:
            kubernetes.io/role: control-plane
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_ARM64_02_HDD
        amd64-01:
          ansible_host: 192.168.2.61
          node_labels:
            kubernetes.io/role: control-plane
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_AMD64_01_HDD
    microk8s_workers:
      hosts:
        arm64-03:
          ansible_host: 192.168.2.53
          node_labels:
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_ARM64_03_HDD
        arm64-04:
          ansible_host: 192.168.2.54
          node_labels:
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_ARM64_04_HDD
        arm64-05:
          ansible_host: 192.168.2.55
          node_labels:
            node.kalaxy2/storage: ssd
            node.kalaxy2/minio: "true"
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_ARM64_05_HDD
        amd64-02:
          ansible_host: 192.168.2.62
          node_labels:
            node.kalaxy2/storage: ssd
            node.kalaxy2/gpu: "true"
            node.kalaxy2/minio: "true"
          node_taints:
            - key: nvidia.com/gpu
              value: present
              effect: NoSchedule
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_AMD64_02_HDD
        amd64-03:
          ansible_host: 192.168.2.63
          node_labels:
            node.kalaxy2/storage: ssd
            node.kalaxy2/gpu: "true"
            node.kalaxy2/minio: "true"
          node_taints:
            - key: nvidia.com/gpu
              value: present
              effect: NoSchedule
          data_disk_by_id: /dev/disk/by-id/REPLACE_ME_AMD64_03_HDD
    microk8s_cluster:
      children:
        microk8s_control_plane:
        microk8s_workers:
