#!/usr/bin/env python3
"""Validate and publish a Kalaxy3 SAGE evidence package.

Uses only the Python standard library. The package is generated by an evidence
synthesis tool, while this script is the repository-side enforcement point.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any, Iterable
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from workflow.evidence_records import (
    FIVE_W_ROWS,
    LIST_FIELDS,
    PUBLICATION_AUTHORITIES,
    REQUIRED_FRONTMATTER,
    REQUIRED_FRONTMATTER_ORDER,
    REQUIRED_TEMPLATE_HEADINGS,
    STATIC_METADATA_ROWS,
)

PACKAGE_SCHEMA_VERSION = "1.2"
RECORD_SCHEMA_VERSION = "1.2"
METADATA_CONTRACT_PATH = "markdown/standards/sage-evidence-metadata-contract-v1.2.json"
INDEXER_PATH = "scripts/sage/sage-index.py"
GENERATED_FILES_MANIFEST = "markdown/evidence/generated-files.json"

ALLOWED_STATUSES = {
    "draft",
    "implemented",
    "validated",
    "accepted",
    "superseded",
    "retired",
    "rejected",
}
ALLOWED_RECORD_TYPES = {
    "installation",
    "architecture-decision",
    "change",
    "verification",
    "incident",
    "experiment",
    "benchmark",
    "operations",
    "security",
    "finops",
}
ALLOWED_ENVIRONMENTS = {
    "homelab",
    "development",
    "test",
    "production",
    "research",
    "shared-platform",
}
ALLOWED_CONFIDENCE = {"high", "medium", "low", "unknown"}
ALLOWED_CATEGORIES = {
    "installation",
    "operations",
    "architecture",
    "decisions",
    "finops",
    "governance",
    "security",
    "incidents",
    "experiments",
    "benchmarks",
    "verification",
}
ALLOWED_NAV_SECTIONS = ALLOWED_CATEGORIES | {"other"}
CANONICAL_UNAVAILABLE = {"not-applicable", "not-captured", "pending"}
EVIDENCE_ID_RE = re.compile(r"^SAGE-K3-[A-Z0-9-]+-\d{8}-\d{3}$")
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
KEY_VALUE_RE = re.compile(r"^[^=;]+=[^=;]+$")
IMPLEMENTATION_TOKEN = "__SAGE_IMPLEMENTATION_COMMIT__"
PUBLISHED_AT_TOKEN = "__SAGE_PUBLISHED_AT__"

FATAL_SECRET_PATTERNS = {
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "kubeconfig client key": re.compile(r"(?mi)^\s*client-key-data:\s*[A-Za-z0-9+/=]{40,}\s*$"),
    "bearer token": re.compile(r"(?i)authorization:\s*bearer\s+[A-Za-z0-9._~-]{20,}"),
    "github token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
}
WARNING_SECRET_PATTERNS = {
    "possible password assignment": re.compile(
        r"(?mi)^\s*(?:password|passwd|token|secret)\s*[:=]\s*(?!<|pending|redacted|none|not-applicable)(\S+)"
    ),
}


class SageError(RuntimeError):
    pass


def run(
    args: list[str],
    *,
    cwd: Path,
    check: bool = True,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        args,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )
    if check and proc.returncode != 0:
        out = (proc.stdout or "").strip()
        err = (proc.stderr or "").strip()
        detail = "\n".join(x for x in [out, err] if x)
        raise SageError(f"Command failed ({proc.returncode}): {' '.join(args)}\n{detail}")
    return proc


def git(repo: Path, *args: str, check: bool = True) -> str:
    return run(["git", *args], cwd=repo, check=check).stdout.strip()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def ensure_repo_root(repo_arg: str | None) -> Path:
    start = Path(repo_arg).expanduser().resolve() if repo_arg else Path.cwd().resolve()
    proc = run(["git", "rev-parse", "--show-toplevel"], cwd=start)
    repo = Path(proc.stdout.strip()).resolve()
    if not (repo / ".git").exists():
        raise SageError(f"Not a normal Git working tree: {repo}")
    return repo


def safe_relpath(value: str, *, field: str) -> PurePosixPath:
    p = PurePosixPath(value)
    if p.is_absolute() or not p.parts or any(part in {"", ".", ".."} for part in p.parts):
        raise SageError(f"Unsafe {field}: {value!r}")
    return p


def zip_entry_is_symlink(info: zipfile.ZipInfo) -> bool:
    mode = info.external_attr >> 16
    return stat.S_ISLNK(mode)


def load_package(package: Path, temp: Path) -> tuple[dict[str, Any], Path]:
    if not package.exists():
        raise SageError(f"Package not found: {package}")
    if package.suffix.lower() != ".zip":
        raise SageError("SAGE packages must be ZIP files")

    with zipfile.ZipFile(package) as zf:
        infos = zf.infolist()
        if len(infos) > 500:
            raise SageError("ZIP contains more than 500 entries")
        total_uncompressed = sum(info.file_size for info in infos)
        if total_uncompressed > 500 * 1024 * 1024:
            raise SageError("ZIP uncompressed payload exceeds 500 MiB")
        names = set()
        for info in infos:
            rel = safe_relpath(info.filename.rstrip("/"), field="ZIP entry") if info.filename.rstrip("/") else None
            if rel is None:
                continue
            if zip_entry_is_symlink(info):
                raise SageError(f"ZIP contains a symbolic link: {info.filename}")
            if info.filename in names:
                raise SageError(f"ZIP contains duplicate entry: {info.filename}")
            names.add(info.filename)
            destination = (temp / Path(*rel.parts)).resolve()
            if temp.resolve() not in destination.parents and destination != temp.resolve():
                raise SageError(f"ZIP path escapes extraction directory: {info.filename}")
        zf.extractall(temp)

    manifest_path = temp / "sage-package.json"
    payload = temp / "payload"
    if not manifest_path.is_file():
        raise SageError("Package is missing sage-package.json")
    if not payload.is_dir():
        raise SageError("Package is missing payload/")

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise SageError(f"Invalid sage-package.json: {exc}") from exc
    if not isinstance(manifest, dict):
        raise SageError("sage-package.json must contain a JSON object")
    return manifest, payload


def require_manifest(manifest: dict[str, Any], key: str, expected_type: type) -> Any:
    if key not in manifest:
        raise SageError(f"Manifest is missing {key!r}")
    value = manifest[key]
    if not isinstance(value, expected_type):
        raise SageError(f"Manifest {key!r} must be {expected_type.__name__}")
    return value


def validate_manifest(manifest: dict[str, Any]) -> None:
    if require_manifest(manifest, "schema_version", str) != PACKAGE_SCHEMA_VERSION:
        raise SageError(
            f"Unsupported package schema_version; expected {PACKAGE_SCHEMA_VERSION}"
        )
    if require_manifest(manifest, "record_schema_version", str) != RECORD_SCHEMA_VERSION:
        raise SageError(
            f"Unsupported record_schema_version; expected {RECORD_SCHEMA_VERSION}"
        )
    if require_manifest(manifest, "metadata_contract_path", str) != METADATA_CONTRACT_PATH:
        raise SageError(
            f"metadata_contract_path must be {METADATA_CONTRACT_PATH}"
        )
    if require_manifest(manifest, "repository", str) != "donb4iu/Kalaxy3":
        raise SageError("Manifest repository must be donb4iu/Kalaxy3")
    branch = require_manifest(manifest, "branch", str)
    if not branch:
        raise SageError("Manifest branch cannot be empty")
    evidence_id = require_manifest(manifest, "evidence_id", str)
    if not EVIDENCE_ID_RE.fullmatch(evidence_id):
        raise SageError(f"Invalid evidence_id: {evidence_id}")

    record_path = safe_relpath(require_manifest(manifest, "record_path", str), field="record_path")
    if len(record_path.parts) < 3 or record_path.parts[0] != "markdown":
        raise SageError("record_path must be under markdown/<category>/")
    if record_path.parts[1] not in ALLOWED_CATEGORIES:
        raise SageError(f"Unsupported record category: {record_path.parts[1]}")
    if record_path.suffix != ".md":
        raise SageError("record_path must end in .md")

    checksum_path = safe_relpath(
        require_manifest(manifest, "record_checksum_path", str), field="record_checksum_path"
    )
    if str(checksum_path) != f"{record_path}.sha256":
        raise SageError("record_checksum_path must equal record_path + .sha256")

    artifact_paths = require_manifest(manifest, "artifact_paths", list)
    if not artifact_paths:
        raise SageError("artifact_paths must include at least the publication manifest or terminal evidence")
    for value in artifact_paths:
        if not isinstance(value, str):
            raise SageError("artifact_paths entries must be strings")
        p = safe_relpath(value, field="artifact path")
        expected_prefix = PurePosixPath("markdown", "evidence-artifacts", evidence_id)
        if p.parts[: len(expected_prefix.parts)] != expected_prefix.parts:
            raise SageError(f"Artifact must be under {expected_prefix}: {value}")

    impl_paths = require_manifest(manifest, "implementation_paths", list)
    for value in impl_paths:
        if not isinstance(value, str):
            raise SageError("implementation_paths entries must be strings")
        p = safe_relpath(value, field="implementation path")
        if p.parts[0] == "markdown" and p.parts[1:2] in [("evidence-artifacts",)]:
            raise SageError("Evidence artifact paths cannot be implementation paths")
        if str(p) in {str(record_path), str(checksum_path)}:
            raise SageError("Evidence files cannot be implementation paths")

    mode = require_manifest(manifest, "publication_mode", str)
    if mode not in {"split", "evidence-only"}:
        raise SageError("publication_mode must be split or evidence-only")
    if mode == "split" and not impl_paths:
        raise SageError("split publication requires implementation_paths")
    if mode == "evidence-only" and impl_paths:
        raise SageError("evidence-only publication must not list implementation_paths")

    require_manifest(manifest, "implementation_commit_message", str)
    require_manifest(manifest, "evidence_commit_message", str)
    files = require_manifest(manifest, "files", list)
    if not files:
        raise SageError("Manifest files list cannot be empty")
    seen: set[str] = set()
    for item in files:
        if not isinstance(item, dict):
            raise SageError("Manifest files entries must be objects")
        path = item.get("path")
        digest = item.get("sha256")
        if not isinstance(path, str) or not isinstance(digest, str):
            raise SageError("Each manifest file needs string path and sha256")
        safe_relpath(path, field="manifest file path")
        if path in seen:
            raise SageError(f"Duplicate manifest file path: {path}")
        seen.add(path)
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise SageError(f"Invalid SHA-256 for {path}")

    required_payload = {str(record_path), *artifact_paths}
    if not required_payload.issubset(seen):
        missing = sorted(required_payload - seen)
        raise SageError(f"Manifest files list omits payload files: {missing}")


def verify_payload_hashes(manifest: dict[str, Any], payload: Path) -> None:
    declared: set[str] = set()
    for item in manifest["files"]:
        rel = safe_relpath(item["path"], field="manifest file path")
        path = payload / Path(*rel.parts)
        if not path.is_file():
            raise SageError(f"Declared payload file missing: {rel}")
        actual = sha256_file(path)
        if actual != item["sha256"]:
            raise SageError(f"Payload checksum mismatch for {rel}: expected {item['sha256']}, got {actual}")
        declared.add(str(rel))

    actual_files = {
        p.relative_to(payload).as_posix()
        for p in payload.rglob("*")
        if p.is_file()
    }
    extra = sorted(actual_files - declared)
    missing = sorted(declared - actual_files)
    if extra or missing:
        raise SageError(f"Payload file inventory mismatch; extra={extra}, missing={missing}")


def unquote_yaml_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_frontmatter(
    text: str,
) -> tuple[dict[str, str], dict[str, list[str]], list[str], str]:
    """Parse the constrained YAML subset used by the SAGE metadata contract.

    The publisher intentionally does not implement general YAML. Top-level
    scalar fields and top-level string lists are parsed. Nested relationships
    are retained only as a required top-level block because claim lineage is
    validated in the record body and publication manifest.
    """
    if not text.startswith("---\n"):
        raise SageError("Evidence record must start with YAML front matter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise SageError("Evidence record front matter is not terminated")
    block = text[4:end]
    body = text[end + 5 :]
    scalars: dict[str, str] = {}
    lists: dict[str, list[str]] = {}
    order: list[str] = []
    current: str | None = None

    for lineno, line in enumerate(block.splitlines(), start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        top = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_]*):(?:\s*(.*))?", line)
        if top:
            key = top.group(1)
            if key in order:
                raise SageError(f"Duplicate front-matter field {key!r} at line {lineno}")
            order.append(key)
            current = key
            value = (top.group(2) or "").strip()
            if value:
                scalars[key] = unquote_yaml_scalar(value)
            else:
                lists.setdefault(key, [])
            continue
        item = re.fullmatch(r"\s{2}-\s+(.+)", line)
        if item and current in LIST_FIELDS:
            lists.setdefault(current, []).append(unquote_yaml_scalar(item.group(1)))
            continue
        if line.startswith(" ") and current == "relationships":
            continue
        raise SageError(
            f"Unsupported front-matter syntax at line {lineno}: {line!r}. "
            f"Schema {RECORD_SCHEMA_VERSION} permits top-level scalars, canonical string lists, "
            "and the nested relationships map only."
        )
    return scalars, lists, order, body


def parse_rfc3339(value: str, field: str) -> dt.datetime:
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise SageError(f"{field} must be RFC3339 with numeric offset: {value!r}") from exc
    if parsed.tzinfo is None or parsed.utcoffset() is None:
        raise SageError(f"{field} must include a numeric UTC offset: {value!r}")
    return parsed


def validate_timezone(value: str, field: str) -> None:
    if value == "UTC":
        return
    try:
        ZoneInfo(value)
    except ZoneInfoNotFoundError as exc:
        raise SageError(f"{field} must be an IANA timezone name or UTC: {value!r}") from exc


def canonical_metadata_value(
    key: str,
    scalars: dict[str, str],
    lists: dict[str, list[str]],
) -> str:
    if key in LIST_FIELDS:
        return "; ".join(lists.get(key, []))
    return scalars.get(key, "")


def parse_markdown_table_rows(section: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for line in section.splitlines():
        match = re.fullmatch(r"\|\s*\*\*(.+?)\*\*\s*\|\s*(.*?)\s*\|", line)
        if match:
            rows.append((match.group(1).strip(), match.group(2).strip()))
    return rows


def validate_metadata_contract_file(repo: Path) -> None:
    path = repo / METADATA_CONTRACT_PATH
    if not path.is_file():
        raise SageError(f"Missing SAGE metadata contract: {METADATA_CONTRACT_PATH}")
    try:
        contract = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SageError(f"Invalid SAGE metadata contract JSON: {exc}") from exc
    if contract.get("contract_version") != RECORD_SCHEMA_VERSION:
        raise SageError("Metadata contract version does not match publisher")
    if contract.get("record_schema_version") != RECORD_SCHEMA_VERSION:
        raise SageError("Metadata contract record schema does not match publisher")
    if contract.get("front_matter_order") != REQUIRED_FRONTMATTER_ORDER:
        raise SageError("Metadata contract front_matter_order differs from publisher")
    if set(contract.get("list_fields", [])) != LIST_FIELDS:
        raise SageError("Metadata contract list_fields differ from publisher")
    rows = [tuple(row) for row in contract.get("static_metadata_rows", [])]
    if rows != STATIC_METADATA_ROWS:
        raise SageError("Metadata contract static_metadata_rows differ from publisher")
    if contract.get("five_w_rows") != FIVE_W_ROWS:
        raise SageError("Metadata contract five_w_rows differ from publisher")
    if set(contract.get("allowed_nav_sections", [])) != ALLOWED_NAV_SECTIONS:
        raise SageError("Metadata contract allowed_nav_sections differ from publisher")
    if contract.get("nav_title_max_length") != 80:
        raise SageError("Metadata contract nav_title_max_length differs from publisher")
    if contract.get("summary_max_length") != 360:
        raise SageError("Metadata contract summary_max_length differs from publisher")


def validate_canonical_frontmatter(
    scalars: dict[str, str],
    lists: dict[str, list[str]],
    order: list[str],
    manifest: dict[str, Any],
    *,
    published: bool,
) -> None:
    missing = [key for key in REQUIRED_FRONTMATTER_ORDER if key not in order]
    extra = [key for key in order if key not in REQUIRED_FRONTMATTER_ORDER]
    if missing or extra:
        raise SageError(f"Front-matter contract mismatch; missing={missing}, extra={extra}")
    if order != REQUIRED_FRONTMATTER_ORDER:
        raise SageError(
            f"Front-matter fields are not in canonical schema {RECORD_SCHEMA_VERSION} order. "
            f"Expected {REQUIRED_FRONTMATTER_ORDER}, got {order}"
        )
    for key in REQUIRED_FRONTMATTER_ORDER:
        if key in LIST_FIELDS:
            values = lists.get(key, [])
            if not values:
                raise SageError(f"Front-matter list {key!r} cannot be empty")
            if "not-applicable" in values and len(values) != 1:
                raise SageError(f"{key} cannot combine not-applicable with other values")
        elif key != "relationships" and not scalars.get(key, "").strip():
            raise SageError(f"Front-matter scalar {key!r} cannot be empty")

    if scalars["schema_version"] != RECORD_SCHEMA_VERSION:
        raise SageError(f"Record schema_version must be {RECORD_SCHEMA_VERSION}")
    if scalars["project"] != "Kalaxy3" or scalars["system"] != "Kalaxy3":
        raise SageError("Record project and system must be Kalaxy3")
    if scalars["repository"] != "donb4iu/Kalaxy3":
        raise SageError("Record repository must be donb4iu/Kalaxy3")
    if scalars["record_path"] != manifest["record_path"]:
        raise SageError("Record record_path does not match package manifest")
    if scalars["branch"] != manifest["branch"]:
        raise SageError("Record branch does not match package manifest")
    if scalars["status"] not in ALLOWED_STATUSES:
        raise SageError(f"Invalid lifecycle status: {scalars['status']}")
    if scalars["record_type"] not in ALLOWED_RECORD_TYPES:
        raise SageError(f"Invalid record_type: {scalars['record_type']}")
    if scalars["environment"] not in ALLOWED_ENVIRONMENTS:
        raise SageError(f"Invalid environment: {scalars['environment']}")
    if scalars["confidence"] not in ALLOWED_CONFIDENCE:
        raise SageError(f"Invalid confidence: {scalars['confidence']}")
    if scalars["confidence"] == "unknown" and scalars["status"] != "draft":
        raise SageError("confidence unknown is allowed only for draft records")
    if scalars["nav_section"] not in ALLOWED_NAV_SECTIONS:
        raise SageError(f"Invalid nav_section: {scalars['nav_section']}")
    if not (1 <= len(scalars["nav_title"]) <= 80):
        raise SageError("nav_title must contain 1..80 characters")
    if not (20 <= len(scalars["summary"]) <= 360):
        raise SageError("summary must contain 20..360 characters")
    if "\n" in scalars["summary"]:
        raise SageError("summary must be a single-line scalar")
    if not scalars["primary_subject"].strip():
        raise SageError("primary_subject cannot be empty")
    try:
        nav_order = int(scalars["nav_order"])
    except ValueError as exc:
        raise SageError("nav_order must be an integer") from exc
    if not 0 <= nav_order <= 9999:
        raise SageError("nav_order must be between 0 and 9999")
    if not EVIDENCE_ID_RE.fullmatch(scalars["evidence_id"]):
        raise SageError(f"Invalid evidence_id: {scalars['evidence_id']}")
    if scalars["evidence_id"] != manifest["evidence_id"]:
        raise SageError("Record evidence_id does not match package manifest")
    expected_artifact_root = f"markdown/evidence-artifacts/{scalars['evidence_id']}"
    if scalars["artifact_root"] != expected_artifact_root:
        raise SageError(f"artifact_root must be {expected_artifact_root}")

    validate_timezone(scalars["local_timezone"], "local_timezone")
    for value in lists["system_timestamp_timezones"]:
        if value != "not-applicable":
            validate_timezone(value, "system_timestamp_timezones")

    timestamp_fields = [
        "work_started_at",
        "work_completed_at",
        "evidence_collected_at",
        "created_at",
        "updated_at",
    ]
    parsed_times: dict[str, dt.datetime] = {}
    for key in timestamp_fields:
        value = scalars[key]
        if key == "updated_at" and not published and value == PUBLISHED_AT_TOKEN:
            continue
        if value == "not-captured":
            if key not in {"work_started_at"}:
                raise SageError(f"{key} cannot be not-captured in schema {RECORD_SCHEMA_VERSION}")
            continue
        parsed_times[key] = parse_rfc3339(value, key)
    if scalars["status"] in {"validated", "accepted"}:
        for key in ["work_completed_at", "evidence_collected_at"]:
            if key not in parsed_times:
                raise SageError(f"{scalars['status']} record requires captured {key}")
    if "work_started_at" in parsed_times and "work_completed_at" in parsed_times:
        if parsed_times["work_started_at"] > parsed_times["work_completed_at"]:
            raise SageError("work_started_at cannot be after work_completed_at")
    if not DATE_RE.fullmatch(scalars["valid_as_of"]):
        raise SageError("valid_as_of must be YYYY-MM-DD")
    try:
        dt.date.fromisoformat(scalars["valid_as_of"])
    except ValueError as exc:
        raise SageError("valid_as_of is not a valid date") from exc
    review_due = scalars["review_due"]
    if review_due != "event-based":
        if not DATE_RE.fullmatch(review_due):
            raise SageError("review_due must be YYYY-MM-DD or event-based")
        try:
            dt.date.fromisoformat(review_due)
        except ValueError as exc:
            raise SageError("review_due is not a valid date") from exc

    for field in ["node_addresses", "endpoints", "components"]:
        for value in lists[field]:
            if value == "not-applicable":
                continue
            if not KEY_VALUE_RE.fullmatch(value):
                raise SageError(f"{field} entry must use name=value: {value!r}")
    nodes = set(lists["nodes"])
    if nodes != {"not-applicable"}:
        for value in lists["node_addresses"]:
            if value == "not-applicable":
                continue
            node, _ = value.split("=", 1)
            if node not in nodes:
                raise SageError(f"node_addresses references node not in nodes: {node}")

    for field in ["cluster", "execution_host", "controller_host", "reviewer"]:
        value = scalars[field]
        if value.lower() in {"n/a", "none", "unknown", "tbd", "later", ""}:
            raise SageError(f"{field} uses noncanonical unavailable value: {value!r}")

    impl = scalars["implementation_commit"]
    if published:
        if impl != "not-applicable" and not SHA_RE.fullmatch(impl):
            raise SageError(
                "Published record must contain a full implementation SHA or not-applicable"
            )
    else:
        if manifest["publication_mode"] == "split" and impl != IMPLEMENTATION_TOKEN:
            raise SageError(
                f"Split package record must use implementation_commit: {IMPLEMENTATION_TOKEN}"
            )
        if manifest["publication_mode"] == "evidence-only" and impl not in {
            IMPLEMENTATION_TOKEN,
            "not-applicable",
        } and not SHA_RE.fullmatch(impl):
            raise SageError("Evidence-only record has invalid implementation_commit")


def validate_record_metadata_table(
    body: str,
    scalars: dict[str, str],
    lists: dict[str, list[str]],
) -> None:
    section = section_text(body, "## Record metadata")
    rows = parse_markdown_table_rows(section)
    expected_labels = [label for label, _ in STATIC_METADATA_ROWS]
    actual_labels = [label for label, _ in rows]
    if actual_labels != expected_labels:
        raise SageError(
            "Record metadata rows are missing, extra, or out of order. "
            f"Expected {expected_labels}, got {actual_labels}"
        )
    for (label, key), (_, observed) in zip(STATIC_METADATA_ROWS, rows):
        expected = canonical_metadata_value(key, scalars, lists)
        if observed != expected:
            raise SageError(
                f"Record metadata mismatch for {label}: expected {expected!r}, got {observed!r}"
            )


def validate_five_w_table(
    body: str,
    scalars: dict[str, str],
    lists: dict[str, list[str]],
) -> None:
    section = section_text(body, "## Five Ws and How")
    rows = parse_markdown_table_rows(section)
    actual_labels = [label for label, _ in rows[:6]]
    if actual_labels != FIVE_W_ROWS:
        raise SageError(
            f"Five Ws and How rows must be exactly {FIVE_W_ROWS}; got {actual_labels}"
        )
    values = {label: value for label, value in rows[:6]}
    for field in ["author", "operator", "owner", "reviewer"]:
        if scalars[field] not in values["Who"]:
            raise SageError(f"Five-W Who row does not contain canonical {field}: {scalars[field]}")
    for field in [
        "work_completed_at",
        "evidence_collected_at",
        "local_timezone",
        "valid_as_of",
        "review_due",
    ]:
        if scalars[field] not in values["When"]:
            raise SageError(f"Five-W When row does not contain canonical {field}: {scalars[field]}")
    for timezone in lists["system_timestamp_timezones"]:
        if timezone not in values["When"]:
            raise SageError(f"Five-W When row omits system timestamp timezone: {timezone}")
    for field in ["environment", "cluster", "execution_host", "controller_host", "record_path"]:
        if scalars[field] not in values["Where"]:
            raise SageError(f"Five-W Where row does not contain canonical {field}: {scalars[field]}")
    for field in ["nodes", "node_addresses", "namespaces", "endpoints"]:
        for value in lists[field]:
            if value != "not-applicable" and value not in values["Where"]:
                raise SageError(f"Five-W Where row omits canonical {field} value: {value}")

def validate_heading_order(body: str) -> None:
    headings = [
        line[3:].rstrip()
        for line in body.splitlines()
        if line.startswith("## ")
    ]
    if headings != REQUIRED_TEMPLATE_HEADINGS:
        raise SageError(
            "Evidence record H2 headings must exactly match the current "
            f"template. Expected {REQUIRED_TEMPLATE_HEADINGS}, got {headings}"
        )


def section_text(body: str, heading_prefix: str) -> str:
    lines = body.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith(heading_prefix):
            start = i + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for i in range(start, len(lines)):
        if lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def validate_claims_and_evidence(body: str) -> None:
    claim_rows = re.findall(r"(?m)^\|\s*`(CLM-\d{3,})`\s*\|(.+)$", body)
    if not claim_rows:
        raise SageError("Claims and evidence matrix contains no CLM rows")
    evidence_headings = re.findall(r"(?m)^###\s+`(EV-\d{3,})`\s+—", body)
    if not evidence_headings:
        raise SageError("Evidence items section contains no EV headings")
    if len(evidence_headings) != len(set(evidence_headings)):
        raise SageError("Duplicate evidence IDs found")
    available = set(evidence_headings)
    for claim_id, rest in claim_rows:
        refs = set(re.findall(r"EV-\d{3,}", rest))
        if not refs:
            raise SageError(f"{claim_id} has no evidence IDs")
        missing = refs - available
        if missing:
            raise SageError(f"{claim_id} references missing evidence IDs: {sorted(missing)}")
        cells = [c.strip().lower() for c in rest.split("|")]
        if "critical" in cells and not refs:
            raise SageError(f"Critical claim {claim_id} lacks evidence")


def scan_secrets(text: str, path: str) -> list[str]:
    warnings: list[str] = []
    for label, pattern in FATAL_SECRET_PATTERNS.items():
        if pattern.search(text):
            raise SageError(f"Potential {label} found in {path}")
    for label, pattern in WARNING_SECRET_PATTERNS.items():
        if pattern.search(text):
            warnings.append(f"WARNING: {label} found in {path}; review before publication")
    return warnings


def validate_record(
    record_path: Path,
    manifest: dict[str, Any],
    *,
    published: bool,
) -> list[str]:
    text = record_path.read_text(encoding="utf-8")
    scalars, lists, order, body = parse_frontmatter(text)
    validate_canonical_frontmatter(
        scalars,
        lists,
        order,
        manifest,
        published=published,
    )

    if published and (IMPLEMENTATION_TOKEN in text or PUBLISHED_AT_TOKEN in text):
        raise SageError("Published record still contains publication tokens")

    validate_heading_order(body)
    if "[TOC]" not in body:
        raise SageError("Schema 1.2 record must contain an explicit [TOC] marker")
    validate_record_metadata_table(body, scalars, lists)
    validate_five_w_table(body, scalars, lists)
    validate_claims_and_evidence(body)

    five_w = section_text(body, "## Five Ws and How")
    if scalars["status"] in {"validated", "accepted"}:
        unchecked = re.findall(r"(?m)^- \[ \] (Who|What|When|Where|Why|How)\b", five_w)
        if unchecked:
            raise SageError(f"Validated/accepted record has incomplete Five-W gate: {unchecked}")
    if scalars["status"] == "accepted" and scalars["reviewer"].strip().lower() in {
        "pending",
        "not-applicable",
        "",
    }:
        raise SageError("Accepted record requires a named reviewer")

    if scalars["status"] in {"validated", "accepted"}:
        checklist = section_text(body, "## Final completion checklist")
        unchecked = re.findall(r"(?m)^- \[ \] (.+)$", checklist)
        if unchecked:
            raise SageError(
                "Validated/accepted record has unchecked final checklist items: "
                + "; ".join(unchecked[:5])
            )

    if "not-captured" in scalars.values() or any(
        "not-captured" in values for values in lists.values()
    ):
        gaps = section_text(body, "## Known limitations, evidence gaps, and risks")
        if "not-captured" not in gaps:
            raise SageError(
                "Every not-captured metadata value must be represented in the evidence-gap section"
            )

    template_markers = [
        "SAGE-K3-<DOMAIN>",
        "<Concise evidence-record title>",
        "<Atomic testable claim>",
        "<exact command or source reference>",
        "<same as ",
        "<semicolon-joined",
    ]
    for marker in template_markers:
        if marker in text:
            raise SageError(f"Unresolved template marker found: {marker}")

    warnings = scan_secrets(text, manifest["record_path"])
    return warnings

def validate_artifacts(payload: Path, manifest: dict[str, Any]) -> list[str]:
    warnings: list[str] = []
    for rel_str in manifest["artifact_paths"]:
        rel = safe_relpath(rel_str, field="artifact path")
        path = payload / Path(*rel.parts)
        if not path.is_file():
            raise SageError(f"Artifact missing from package: {rel}")
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        warnings.extend(scan_secrets(text, str(rel)))
    return warnings


def ensure_repo_contract(repo: Path, manifest: dict[str, Any]) -> None:
    standard = repo / "markdown/standards/kalaxy3-sage-evidence-record-standard.md"
    template = repo / "markdown/templates/sage-evidence-record-template.md"
    process = repo / "markdown/standards/kalaxy3-sage-evidence-publication-process.md"
    if not standard.is_file():
        raise SageError(f"Missing SAGE standard: {standard.relative_to(repo)}")
    if not template.is_file():
        raise SageError(f"Missing SAGE template: {template.relative_to(repo)}")
    if not process.is_file():
        raise SageError(f"Missing SAGE publication process: {process.relative_to(repo)}")
    indexer = repo / INDEXER_PATH
    registry = repo / "markdown/evidence/legacy-record-registry.json"
    if not indexer.is_file():
        raise SageError(f"Missing SAGE indexer: {INDEXER_PATH}")
    if not registry.is_file():
        raise SageError("Missing legacy evidence registry")
    validate_metadata_contract_file(repo)
    current_branch = git(repo, "branch", "--show-current")
    if current_branch != manifest["branch"]:
        raise SageError(f"Current branch is {current_branch!r}; package requires {manifest['branch']!r}")
    remote_url = git(repo, "remote", "get-url", "origin", check=False)
    if remote_url and "donb4iu/Kalaxy3" not in remote_url:
        raise SageError(f"origin does not appear to be donb4iu/Kalaxy3: {remote_url}")


def ensure_clean_index(repo: Path) -> None:
    proc = run(["git", "diff", "--cached", "--quiet"], cwd=repo, check=False)
    if proc.returncode not in {0, 1}:
        raise SageError("Unable to inspect Git index")
    if proc.returncode == 1:
        raise SageError("Git index already contains staged changes; unstage them before publishing")


def fetch_and_require_up_to_date(repo: Path, branch: str, remote: str) -> None:
    git(repo, "fetch", remote, branch)
    upstream = f"{remote}/{branch}"
    local = git(repo, "rev-parse", "HEAD")
    remote_sha = git(repo, "rev-parse", upstream)
    base = git(repo, "merge-base", "HEAD", upstream)
    if local == remote_sha:
        return
    if base == local:
        # Local branch is behind. Rebase before publication while preserving
        # the uncommitted implementation working tree.
        git(repo, "pull", "--rebase", "--autostash", remote, branch)
        return
    if base == remote_sha:
        # Local branch is ahead; publication can continue.
        return
    raise SageError(
        f"Local {branch} and {upstream} have diverged. Resolve divergence before SAGE publication."
    )


def modified_for_paths(repo: Path, paths: Iterable[str]) -> list[str]:
    path_list = list(paths)
    if not path_list:
        return []
    out = git(repo, "status", "--porcelain=v1", "--", *path_list)
    return [line for line in out.splitlines() if line.strip()]


def stage_exact(repo: Path, paths: list[str]) -> None:
    if not paths:
        return
    git(repo, "add", "-A", "--", *paths)
    run(["git", "diff", "--cached", "--check"], cwd=repo)
    staged = git(repo, "diff", "--cached", "--name-only").splitlines()
    unexpected = sorted(set(staged) - set(paths))
    missing = sorted(set(paths) - set(staged))
    if unexpected:
        raise SageError(f"Unexpected staged paths: {unexpected}")
    if missing:
        # Existing unchanged paths are not errors, but split mode requires at
        # least one staged implementation change.
        changed = modified_for_paths(repo, missing)
        if changed:
            raise SageError(f"Changed paths were not staged: {missing}")


def commit(repo: Path, message: str) -> str:
    if not message.strip():
        raise SageError("Commit message cannot be empty")
    git(repo, "commit", "-m", message)
    return git(repo, "rev-parse", "HEAD")


def copy_payload(payload: Path, repo: Path, manifest: dict[str, Any]) -> list[str]:
    evidence_paths = [manifest["record_path"], *manifest["artifact_paths"]]
    for rel_str in evidence_paths:
        rel = safe_relpath(rel_str, field="evidence path")
        source = payload / Path(*rel.parts)
        destination = repo / Path(*rel.parts)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return evidence_paths


def replace_publication_tokens(record: Path, implementation_sha: str) -> None:
    text = record.read_text(encoding="utf-8")
    if IMPLEMENTATION_TOKEN in text:
        text = text.replace(IMPLEMENTATION_TOKEN, implementation_sha)
    elif f"implementation_commit: {implementation_sha}" not in text:
        fm, _, _, _ = parse_frontmatter(text)
        if fm.get("implementation_commit") not in {"not-applicable", implementation_sha}:
            raise SageError("Record lacks the implementation commit token")
    published_at = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    text = text.replace(PUBLISHED_AT_TOKEN, published_at)
    record.write_text(text, encoding="utf-8")


def write_record_checksum(repo: Path, manifest: dict[str, Any]) -> str:
    record_rel = manifest["record_path"]
    checksum_rel = manifest["record_checksum_path"]
    digest = sha256_file(repo / record_rel)
    (repo / checksum_rel).write_text(f"{digest}  {record_rel}\n", encoding="utf-8")
    return checksum_rel


def write_publication_manifest(
    repo: Path,
    manifest: dict[str, Any],
    implementation_sha: str,
) -> str:
    evidence_id = manifest["evidence_id"]
    rel = f"markdown/evidence-artifacts/{evidence_id}/publication-manifest.json"
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    published = dict(manifest)
    published["resolved_implementation_commit"] = implementation_sha
    published["published_at"] = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    published["standard_path"] = "markdown/standards/kalaxy3-sage-evidence-record-standard.md"
    published["standard_sha256"] = sha256_file(repo / published["standard_path"])
    published["template_path"] = "markdown/templates/sage-evidence-record-template.md"
    published["template_sha256"] = sha256_file(repo / published["template_path"])
    published["metadata_contract_path"] = METADATA_CONTRACT_PATH
    published["metadata_contract_sha256"] = sha256_file(
        repo / published["metadata_contract_path"]
    )
    published["publication_process_path"] = (
        "markdown/standards/kalaxy3-sage-evidence-publication-process.md"
    )
    published["publication_process_sha256"] = sha256_file(
        repo / published["publication_process_path"]
    )
    published["evidence_indexer_path"] = INDEXER_PATH
    published["evidence_indexer_sha256"] = sha256_file(repo / INDEXER_PATH)
    published["legacy_registry_path"] = "markdown/evidence/legacy-record-registry.json"
    published["legacy_registry_sha256"] = sha256_file(
        repo / published["legacy_registry_path"]
    )
    # Package hashes describe the original package payload. The final record
    # checksum is stored separately after token replacement.
    path.write_text(json.dumps(published, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return rel


def verify_record_checksum(repo: Path, manifest: dict[str, Any]) -> None:
    record_rel = manifest["record_path"]
    checksum_rel = manifest["record_checksum_path"]
    line = (repo / checksum_rel).read_text(encoding="utf-8").strip()
    expected = f"{sha256_file(repo / record_rel)}  {record_rel}"
    if line != expected:
        raise SageError("Final evidence-record checksum verification failed")


def rebase_repair_if_needed(
    repo: Path,
    manifest: dict[str, Any],
    implementation_sha: str,
    remote: str,
) -> tuple[str, str]:
    branch = manifest["branch"]
    git(repo, "fetch", remote, branch)
    upstream = f"{remote}/{branch}"
    proc = run(["git", "merge-base", "--is-ancestor", upstream, "HEAD"], cwd=repo, check=False)
    if proc.returncode == 0:
        return implementation_sha, git(repo, "rev-parse", "HEAD")
    if proc.returncode != 1:
        raise SageError("Unable to compare local branch to upstream")

    mode = manifest["publication_mode"]
    try:
        git(repo, "rebase", upstream)
    except SageError:
        git(repo, "rebase", "--abort", check=False)
        raise
    evidence_sha = git(repo, "rev-parse", "HEAD")
    if mode == "split":
        new_impl = git(repo, "rev-parse", "HEAD~1")
    else:
        new_impl = manifest.get("evidence_only_implementation_commit") or git(repo, "rev-parse", "HEAD~1")

    if new_impl != implementation_sha:
        record = repo / manifest["record_path"]
        text = record.read_text(encoding="utf-8")
        if implementation_sha not in text:
            raise SageError("Rebase changed implementation SHA, but old SHA is not present in evidence record")
        record.write_text(text.replace(implementation_sha, new_impl), encoding="utf-8")
        write_record_checksum(repo, manifest)
        publication_manifest = (
            repo
            / "markdown/evidence-artifacts"
            / manifest["evidence_id"]
            / "publication-manifest.json"
        )
        data = json.loads(publication_manifest.read_text(encoding="utf-8"))
        data["resolved_implementation_commit"] = new_impl
        data["published_at"] = dt.datetime.now().astimezone().isoformat(timespec="seconds")
        publication_manifest.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        evidence_paths = [
            manifest["record_path"],
            manifest["record_checksum_path"],
            *manifest["artifact_paths"],
            publication_manifest.relative_to(repo).as_posix(),
        ]
        git(repo, "add", "--", *sorted(set(evidence_paths)))
        run(["git", "diff", "--cached", "--check"], cwd=repo)
        git(repo, "commit", "--amend", "--no-edit")
        evidence_sha = git(repo, "rev-parse", "HEAD")
        implementation_sha = new_impl
    return implementation_sha, evidence_sha


def _generated_manifest_paths(repo: Path, *, required: bool) -> list[str]:
    """Read and validate stable generated paths from the evidence manifest."""
    manifest_path = repo / GENERATED_FILES_MANIFEST
    if not manifest_path.is_file():
        if required:
            raise SageError(
                "Evidence indexer did not produce generated-files.json"
            )
        return []

    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SageError(f"Invalid generated-files.json: {exc}") from exc

    paths = data.get("generated_paths")
    removed = data.get("removed_paths", [])
    if not isinstance(paths, list) or not all(
        isinstance(x, str) for x in paths
    ):
        raise SageError(
            "generated-files.json must contain generated_paths"
        )
    if not isinstance(removed, list) or not all(
        isinstance(x, str) for x in removed
    ):
        raise SageError(
            "generated-files.json removed_paths must be a list"
        )

    safe = [
        str(safe_relpath(x, field="generated catalog path"))
        for x in paths
    ]
    for rel in safe:
        if not rel.startswith("markdown/evidence/"):
            raise SageError(
                f"Generated catalog path outside markdown/evidence: {rel}"
            )
    return sorted(set(safe))


def reconcile_evidence_catalog(repo: Path) -> list[str]:
    """Reconcile stable generated state and return exact publication scope."""
    indexer = repo / INDEXER_PATH
    if not indexer.is_file():
        raise SageError(
            f"Missing SAGE evidence indexer: {INDEXER_PATH}"
        )

    previous = _generated_manifest_paths(repo, required=False)
    run(
        [sys.executable, INDEXER_PATH, "reconcile", "--repo", str(repo)],
        cwd=repo,
    )
    current = _generated_manifest_paths(repo, required=True)

    removed = sorted(set(previous) - set(current))
    safe = sorted(set([*current, *removed]))
    for rel in safe:
        if not rel.startswith("markdown/evidence/"):
            raise SageError(
                f"Generated catalog path outside markdown/evidence: {rel}"
            )
    return safe



def package_check(package: Path, repo: Path | None = None) -> tuple[dict[str, Any], list[str]]:
    warnings: list[str] = []
    with tempfile.TemporaryDirectory(prefix="sage-package-") as td:
        temp = Path(td)
        manifest, payload = load_package(package, temp)
        validate_manifest(manifest)
        verify_payload_hashes(manifest, payload)
        record_rel = safe_relpath(manifest["record_path"], field="record_path")
        warnings.extend(validate_record(payload / Path(*record_rel.parts), manifest, published=False))
        warnings.extend(validate_artifacts(payload, manifest))
        if repo is not None:
            ensure_repo_contract(repo, manifest)
    return manifest, warnings


def publish(package: Path, repo: Path, *, push: bool, remote: str) -> None:
    with tempfile.TemporaryDirectory(prefix="sage-package-") as td:
        temp = Path(td)
        manifest, payload = load_package(package, temp)
        validate_manifest(manifest)
        verify_payload_hashes(manifest, payload)
        record_rel = safe_relpath(manifest["record_path"], field="record_path")
        warnings = validate_record(payload / Path(*record_rel.parts), manifest, published=False)
        warnings.extend(validate_artifacts(payload, manifest))
        ensure_repo_contract(repo, manifest)
        ensure_clean_index(repo)
        fetch_and_require_up_to_date(repo, manifest["branch"], remote)

        implementation_paths = list(manifest["implementation_paths"])
        implementation_sha: str
        if manifest["publication_mode"] == "split":
            changed = modified_for_paths(repo, implementation_paths)
            if not changed:
                raise SageError("No implementation changes found for split publication")
            stage_exact(repo, implementation_paths)
            if not git(repo, "diff", "--cached", "--name-only"):
                raise SageError("Implementation staging produced no changes")
            implementation_sha = commit(repo, manifest["implementation_commit_message"])
        else:
            requested = manifest.get("evidence_only_implementation_commit")
            if requested:
                if not isinstance(requested, str) or not SHA_RE.fullmatch(requested):
                    raise SageError("evidence_only_implementation_commit must be a full Git SHA")
                git(repo, "cat-file", "-e", f"{requested}^{{commit}}")
                implementation_sha = requested
            else:
                implementation_sha = git(repo, "rev-parse", "HEAD")

        evidence_paths = copy_payload(payload, repo, manifest)
        record = repo / manifest["record_path"]
        replace_publication_tokens(record, implementation_sha)
        checksum_rel = write_record_checksum(repo, manifest)
        publication_manifest_rel = write_publication_manifest(repo, manifest, implementation_sha)
        evidence_paths.extend([checksum_rel, publication_manifest_rel])
        catalog_paths = reconcile_evidence_catalog(repo)
        evidence_paths.extend(catalog_paths)
        evidence_paths = sorted(set(evidence_paths))

        # Validate final files after deterministic token replacement.
        warnings.extend(validate_record(record, manifest, published=True))
        verify_record_checksum(repo, manifest)
        run(["git", "diff", "--check"], cwd=repo)

        stage_exact(repo, evidence_paths)
        evidence_sha = commit(repo, manifest["evidence_commit_message"])

        if push:
            implementation_sha, evidence_sha = rebase_repair_if_needed(
                repo,
                manifest,
                implementation_sha,
                remote,
            )
            git(repo, "push", remote, manifest["branch"])

        status = git(repo, "status", "--porcelain=v1")
        if status:
            # Unrelated untracked/modified files are permitted only when they
            # predated publication. Report them prominently instead of claiming
            # a clean tree.
            print("\nPublication completed, but the working tree is not clean:")
            print(status)
        else:
            print("\nPublication completed with a clean working tree.")

        print(f"Evidence ID:           {manifest['evidence_id']}")
        print(f"Implementation commit: {implementation_sha}")
        print(f"Evidence commit:       {evidence_sha}")
        print(f"Record:                {manifest['record_path']}")
        print(f"Checksum:              {manifest['record_checksum_path']}")
        if push:
            print(f"Published to:          {remote}/{manifest['branch']}")
        for warning in sorted(set(warnings)):
            print(warning, file=sys.stderr)


def metadata_contract_document() -> dict[str, Any]:
    return {
        "contract_version": RECORD_SCHEMA_VERSION,
        "record_schema_version": RECORD_SCHEMA_VERSION,
        "front_matter_order": REQUIRED_FRONTMATTER_ORDER,
        "list_fields": sorted(LIST_FIELDS),
        "static_metadata_rows": [list(row) for row in STATIC_METADATA_ROWS],
        "five_w_rows": FIVE_W_ROWS,
        "allowed_nav_sections": sorted(ALLOWED_NAV_SECTIONS),
        "nav_title_max_length": 80,
        "summary_max_length": 360,
        "allowed_not_available_values": sorted(CANONICAL_UNAVAILABLE),
        "canonical_list_separator": "; ",
        "timestamp_format": "RFC3339 with numeric UTC offset",
        "timezone_format": "IANA timezone name or UTC",
    }


def make_dummy_record(evidence_id: str, record_path: str) -> str:
    artifact_root = f"markdown/evidence-artifacts/{evidence_id}"
    front = f'''---
evidence_id: {evidence_id}
schema_version: "1.2"
title: SAGE publication self-test
nav_title: Test SAGE publication and legacy indexing
nav_section: governance
nav_order: 10
summary: Validates split publication, canonical navigation metadata, and preservation of legacy evidence in generated catalogs.
primary_subject: SAGE publisher
project: Kalaxy3
record_type: operations
status: validated
classification: internal
work_session: SAGE publisher schema 1.2 self-test
work_started_at: 2026-07-25T17:00:00-05:00
work_completed_at: 2026-07-25T17:01:00-05:00
evidence_collected_at: 2026-07-25T17:02:00-05:00
created_at: 2026-07-25T17:03:00-05:00
updated_at: {PUBLISHED_AT_TOKEN}
valid_as_of: 2026-07-25
review_due: event-based
local_timezone: America/Chicago
system_timestamp_timezones:
  - UTC
owner: self-test-owner
author: self-test-author
operator: self-test-operator
reviewer: pending
environment: test
system: Kalaxy3
cluster: not-applicable
execution_host: temporary-repository
controller_host: self-test-controller
nodes:
  - not-applicable
node_addresses:
  - not-applicable
namespaces:
  - not-applicable
endpoints:
  - not-applicable
components:
  - SAGE-publisher=self-test-1.2
repository: donb4iu/Kalaxy3
branch: main
implementation_commit: {IMPLEMENTATION_TOKEN}
record_path: {record_path}
artifact_root: {artifact_root}
confidence: high
tags:
  - sage
  - self-test
relationships:
  verifies:
    - SAGE publisher self-test
  depends_on:
    - none
  supersedes:
    - none
  superseded_by:
    - none
  related_to:
    - none
  conflicts_with:
    - none
  generated_by:
    - scripts/sage/sage-publish.py
  implemented_by:
    - {IMPLEMENTATION_TOKEN}
  revalidated_by:
    - none
---

# SAGE publication self-test

## Executive summary

The temporary publication test validated the schema 1.2 metadata and navigation contracts,
created separate implementation and evidence commits, pushed both commits, and
left the test repository clean.

[TOC]

## Record metadata

| Field | Value |
|---|---|
| **Evidence ID** | {evidence_id} |
| **Schema version** | 1.2 |
| **Project** | Kalaxy3 |
| **Title** | SAGE publication self-test |
| **Navigation title** | Test SAGE publication and legacy indexing |
| **Navigation section** | governance |
| **Navigation order** | 10 |
| **Summary** | Validates split publication, canonical navigation metadata, and preservation of legacy evidence in generated catalogs. |
| **Primary subject** | SAGE publisher |
| **Record type** | operations |
| **Status** | validated |
| **Classification** | internal |
| **Work session** | SAGE publisher schema 1.2 self-test |
| **Started** | 2026-07-25T17:00:00-05:00 |
| **Completed** | 2026-07-25T17:01:00-05:00 |
| **Evidence collected** | 2026-07-25T17:02:00-05:00 |
| **Record created** | 2026-07-25T17:03:00-05:00 |
| **Record updated** | {PUBLISHED_AT_TOKEN} |
| **Local timezone** | America/Chicago |
| **System timestamp timezone(s)** | UTC |
| **Valid as of** | 2026-07-25 |
| **Review due** | event-based |
| **Target record path** | {record_path} |
| **Artifact root** | {artifact_root} |
| **Repository** | donb4iu/Kalaxy3 |
| **Branch** | main |
| **Implementation commit** | {IMPLEMENTATION_TOKEN} |
| **Environment** | test |
| **System** | Kalaxy3 |
| **Cluster** | not-applicable |
| **Execution host** | temporary-repository |
| **Controller host** | self-test-controller |
| **Nodes** | not-applicable |
| **Node addresses** | not-applicable |
| **Namespaces** | not-applicable |
| **Endpoints** | not-applicable |
| **Components and versions** | SAGE-publisher=self-test-1.2 |
| **Owner** | self-test-owner |
| **Author** | self-test-author |
| **Operator** | self-test-operator |
| **Reviewer** | pending |
| **Confidence** | high |

## Navigation contract

- The formal title identifies the evidentiary claim.
- The navigation title provides the concise generated-index label.
- The section, order, summary, and subject values are authoritative.

## Five Ws and How

| Requirement | Answer |
|---|---|
| **Who** | Author self-test-author, operator self-test-operator, owner self-test-owner, and reviewer pending exercised the workflow. |
| **What** | The test validates canonical metadata and split Git publication. |
| **When** | Completed 2026-07-25T17:01:00-05:00; evidence collected 2026-07-25T17:02:00-05:00; local timezone America/Chicago; system timestamps UTC; valid as of 2026-07-25; review due event-based. |
| **Where** | Environment test; cluster not-applicable; execution host temporary-repository; controller self-test-controller; record {record_path}. |
| **Why** | The publisher must prevent metadata and Git-workflow drift. |
| **How** | A temporary repository and bare remote execute the complete check, two-commit publication, push, and clean-tree verification. |

### Five-W completeness gate

- [x] Who is complete and agrees with metadata.
- [x] What is complete.
- [x] When is complete, uses canonical timestamps, and includes timezone context.
- [x] Where is complete at repository and runtime levels and agrees with metadata.
- [x] Why includes rationale, alternatives, and tradeoffs.
- [x] How is reproducible and verifiable.

## Scope and boundaries

The test covers schema validation and Git publication in a temporary repository.
It does not validate the truth of arbitrary engineering evidence.

## Final accepted state

The temporary repository contains separate implementation and evidence commits,
the evidence record contains the implementation SHA, and the working tree is
clean.

## Claims and evidence matrix

| Claim ID | Claim | Criticality | Evidence IDs | Result | Confidence |
|---|---|---|---|---|---|
| `CLM-001` | The publisher completes a schema 1.2 split publication and reconciles legacy evidence. | critical | `EV-001` | supported | high |

## Problem and decision rationale

The self-test prevents untested changes to the publication contract.

## Architecture or change description

Temporary working repository to temporary bare remote.

## Source of truth and implementation lineage

The executing publisher and metadata contract are the source of truth.

## Prerequisites and assumptions

Python and Git are available in the test environment.

## Implementation procedure

The self-test generates a package, validates it, publishes it, and pushes it.

## Evidence items

### `EV-001` — Temporary publication result

| Field | Value |
|---|---|
| Classification | `generated-artifact` |
| Supports or contradicts | `CLM-001` |
| Collected by | self-test-operator |
| Collected at | 2026-07-25T17:02:00-05:00 |
| Execution source | temporary-repository |
| Target | temporary Git remote |
| Tool and version | SAGE-publisher=self-test-1.2 |
| Expected result | Two commits, successful push, clean tree |
| Actual result | pass |
| Confidence | high |
| Sensitive data | none |
| Artifact | inline |

**Command, query, source, or observation**

```bash
python3 scripts/sage/sage-publish.py self-test
```

**Observed result**

```text
SAGE publication self-test: PASS
```

**Interpretation**

The result proves the tested publication path, not the truth of external
session evidence.

## Verification and acceptance criteria

| Criterion ID | Requirement | Test or evidence | Expected | Observed | Result |
|---|---|---|---|---|---|
| `AC-001` | Split publication succeeds | `EV-001` | two commits and clean tree | observed | pass |

## Idempotency and repeatability

The self-test creates a fresh isolated environment on every run.

## Security, privacy, and evidence handling

Synthetic values only; no secrets are used.

## Reliability, recovery, rollback, and rebuild

Temporary files are removed automatically. Failure returns a nonzero exit.

## Operational considerations and observability

The command output reports commits, paths, push state, and tree cleanliness.

## Known limitations, evidence gaps, and risks

No material metadata gap is present in the synthetic record.

## Troubleshooting

Inspect the first reported contract or Git failure.

## Freshness, revalidation, and supersession

Revalidate whenever the publisher, standard, template, process, package schema,
or metadata contract changes.

## Final completion checklist and reviewer acceptance

- [x] Evidence ID is unique and permanent.
- [x] Schema version is 1.2.
- [x] Front matter follows the exact metadata contract and order.
- [x] Record metadata exactly mirrors front matter.
- [x] Status accurately reflects completeness.
- [x] Owner, author, operator, and reviewer are identified.
- [x] Five Ws and How agree with canonical metadata.
- [x] Scope and nonclaims are explicit.
- [x] Implementation commit is recorded or validly not-applicable.
- [x] Relationships and supersession fields are complete.
- [x] Every critical claim has supporting evidence.
- [x] Expected and observed results are separated.
- [x] Direct observations identify source, target, time, and tool version.
- [x] Derived conclusions reference evidence IDs.
- [x] Assumptions and planned work are marked.
- [x] Failed attempts are separated from final state.
- [x] Idempotency or repeatability is proven or not-applicable.
- [x] Every not-captured value has an evidence gap.
- [x] Secrets and sensitive data are excluded or redacted.
- [x] Security limitations and residual risks are recorded.
- [x] Rollback, rebuild, and data-durability impacts are documented.
- [x] Operational health checks are documented.
- [x] Known limitations and gaps have owners or triggers.
- [x] Revalidation criteria are defined.

## Git review and publication

The self-test uses the same publisher functions as normal publication.

## Appendices and raw artifacts

The synthetic terminal artifact is stored under the evidence ID directory.
'''
    return front


def self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="sage-self-test-") as td:
        base = Path(td)
        remote = base / "donb4iu" / "Kalaxy3.git"
        remote.parent.mkdir(parents=True)
        repo = base / "repo"
        run(["git", "init", "--bare", str(remote)], cwd=base)
        run(["git", "init", "-b", "main", str(repo)], cwd=base)
        git(repo, "config", "user.name", "SAGE Self Test")
        git(repo, "config", "user.email", "sage-self-test@example.invalid")
        git(repo, "remote", "add", "origin", str(remote))
        (repo / "markdown/standards").mkdir(parents=True)
        (repo / "markdown/templates").mkdir(parents=True)
        (repo / "markdown/standards/kalaxy3-sage-evidence-record-standard.md").write_text(
            "# test standard\n", encoding="utf-8"
        )
        (repo / "markdown/templates/sage-evidence-record-template.md").write_text(
            "# test template\n", encoding="utf-8"
        )
        (repo / "markdown/standards/kalaxy3-sage-evidence-publication-process.md").write_text(
            "# test publication process\n", encoding="utf-8"
        )
        (repo / "scripts/sage").mkdir(parents=True)
        shutil.copy2(Path(__file__).with_name("sage-index.py"), repo / INDEXER_PATH)
        (repo / "markdown/evidence").mkdir(parents=True)
        (repo / "markdown/evidence/legacy-record-registry.json").write_text(
            json.dumps({
                "registry_version": "1.0",
                "candidate_roots": ["markdown/installation", "markdown/operations"],
                "exclude_paths": [],
                "records": [],
            }, indent=2) + "\n",
            encoding="utf-8",
        )
        (repo / "markdown/installation").mkdir(parents=True)
        (repo / "markdown/installation/legacy-node-evidence.md").write_text(
            "# AMD64 node and Longhorn installation evidence\n\n"
            "Project: Kalaxy3\n"
            "Completed: July 19, 2026, America/Chicago\n"
            "Node: amd64-01\n"
            "Node address: 192.168.2.61\n"
            "Longhorn version: v1.12.0\n",
            encoding="utf-8",
        )
        (repo / METADATA_CONTRACT_PATH).write_text(
            json.dumps(metadata_contract_document(), indent=2) + "\n",
            encoding="utf-8",
        )

        # Install the production retrieval contract into the same isolated
        # repository used by the publication self-test. This proves that
        # evidence created through the publisher is subsequently consumable
        # through the canonical retrieval interface.
        source_root = Path(__file__).resolve().parents[2]
        shutil.copy2(
            source_root / "sage-evidence-retrieval-policy.json",
            repo / "sage-evidence-retrieval-policy.json",
        )
        shutil.copy2(
            Path(__file__).with_name("sage-evidence-retrieval.py"),
            repo / "scripts/sage/sage-evidence-retrieval.py",
        )
        shutil.copy2(
            Path(__file__).with_name("sage_evidence_retrieval.py"),
            repo / "scripts/sage/sage_evidence_retrieval.py",
        )
        retrieval_registries = {
            "sage-lessons.json": {"lessons": []},
            "sage-actionable-failures.json": {"failures": {}},
            "sage-improvement-actions.json": {"actions": []},
            "sage-post-session-review-registry.json": {"reviews": []},
        }
        for relative, payload in retrieval_registries.items():
            (repo / relative).write_text(
                json.dumps(payload, indent=2) + "\n",
                encoding="utf-8",
            )

        (repo / "implementation.txt").write_text("before\n", encoding="utf-8")
        git(repo, "add", ".")
        git(repo, "commit", "-m", "Initialize test repository")
        git(repo, "push", "-u", "origin", "main")
        (repo / "implementation.txt").write_text("after\n", encoding="utf-8")

        evidence_id = "SAGE-K3-TEST-20260725-001"
        record_rel = "markdown/operations/sage-publication-self-test.md"
        artifact_rel = f"markdown/evidence-artifacts/{evidence_id}/terminal.md"
        package_dir = base / "package"
        payload = package_dir / "payload"
        (payload / Path(record_rel).parent).mkdir(parents=True)
        (payload / Path(artifact_rel).parent).mkdir(parents=True)
        (payload / record_rel).write_text(make_dummy_record(evidence_id, record_rel), encoding="utf-8")
        (payload / artifact_rel).write_text("# self-test artifact\n", encoding="utf-8")
        files = []
        for rel in [record_rel, artifact_rel]:
            files.append({"path": rel, "sha256": sha256_file(payload / rel)})
        manifest = {
            "schema_version": PACKAGE_SCHEMA_VERSION,
            "record_schema_version": RECORD_SCHEMA_VERSION,
            "metadata_contract_path": METADATA_CONTRACT_PATH,
            "repository": "donb4iu/Kalaxy3",
            "branch": "main",
            "evidence_id": evidence_id,
            "record_path": record_rel,
            "record_checksum_path": record_rel + ".sha256",
            "artifact_paths": [artifact_rel],
            "implementation_paths": ["implementation.txt"],
            "publication_mode": "split",
            "implementation_commit_message": "Apply self-test implementation",
            "evidence_commit_message": "Add self-test SAGE evidence",
            "files": files,
        }
        package_dir.mkdir(exist_ok=True)
        (package_dir / "sage-package.json").write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
        )
        package_zip = base / "self-test.zip"
        with zipfile.ZipFile(package_zip, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in package_dir.rglob("*"):
                if path.is_file():
                    zf.write(path, path.relative_to(package_dir).as_posix())
        publish(package_zip, repo, push=True, remote="origin")
        log = git(repo, "log", "--oneline", "-3")
        if "Add self-test SAGE evidence" not in log or "Apply self-test implementation" not in log:
            raise SageError("Self-test commits were not created")
        catalog_path = repo / "markdown/evidence/catalog.json"
        if not catalog_path.is_file():
            raise SageError("Self-test did not generate evidence catalog")
        catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
        classes = {item["record_class"] for item in catalog.get("records", [])}
        if "sage-current" not in classes or "legacy-evidence" not in classes:
            raise SageError(f"Self-test catalog did not preserve both classes: {classes}")
        run([sys.executable, INDEXER_PATH, "check", "--repo", str(repo)], cwd=repo)

        retrieval = subprocess.run(
            [
                sys.executable,
                "scripts/sage/sage-evidence-retrieval.py",
                "retrieve",
                "--request",
                "SAGE publication self-test evidence",
                "--limit",
                "10",
            ],
            cwd=repo,
            text=True,
            capture_output=True,
            check=False,
        )
        if retrieval.returncode != 0:
            raise SageError(
                "Published evidence retrieval failed: "
                + (retrieval.stderr.strip() or retrieval.stdout.strip())
            )
        try:
            retrieval_payload = json.loads(retrieval.stdout)
        except json.JSONDecodeError as exc:
            raise SageError(
                f"Published evidence retrieval returned invalid JSON: {exc}"
            ) from exc

        retrieved = [
            item
            for item in retrieval_payload.get("results", [])
            if item.get("identifier") == evidence_id
        ]
        if len(retrieved) != 1:
            identifiers = [
                item.get("identifier")
                for item in retrieval_payload.get("results", [])
            ]
            raise SageError(
                "Published evidence was not uniquely retrievable: "
                f"{identifiers}"
            )
        published_result = retrieved[0]
        if published_result.get("source_path") != "markdown/evidence/catalog.json":
            raise SageError("Published evidence retrieval bypassed the generated catalog")
        source_section = published_result.get("source_section", {})
        if source_section.get("source_document") != record_rel:
            raise SageError(
                "Published evidence retrieval did not preserve source-document provenance"
            )
        if not published_result.get("applicable_facts"):
            raise SageError("Published evidence retrieval returned no applicable facts")

        for item in retrieval_payload.get("results", []):
            item["disposition"] = "reviewed-not-applicable"
            item["disposition_rationale"] = (
                "Retrieved during publication round-trip validation."
            )
        published_result["disposition"] = "applied"
        published_result["disposition_rationale"] = (
            "Published evidence was retrieved through the canonical interface "
            "and used to prove bidirectional evidence accessibility."
        )
        retrieval_result = base / "retrieval-result.json"
        retrieval_result.write_text(
            json.dumps(retrieval_payload, indent=2) + "\n",
            encoding="utf-8",
        )
        validation = subprocess.run(
            [
                sys.executable,
                "scripts/sage/sage-evidence-retrieval.py",
                "validate",
                "--input",
                str(retrieval_result),
                "--require-final",
            ],
            cwd=repo,
            text=True,
            capture_output=True,
            check=False,
        )
        if validation.returncode != 0:
            raise SageError(
                "Finalized retrieval disposition validation failed: "
                + (validation.stderr.strip() or validation.stdout.strip())
            )

        unrelated = subprocess.run(
            [
                sys.executable,
                "scripts/sage/sage-evidence-retrieval.py",
                "retrieve",
                "--request",
                "Rotate internal TLS certificates",
                "--limit",
                "10",
            ],
            cwd=repo,
            text=True,
            capture_output=True,
            check=False,
        )
        if unrelated.returncode != 0:
            raise SageError(
                "Unrelated retrieval negative case failed to execute: "
                + (unrelated.stderr.strip() or unrelated.stdout.strip())
            )
        try:
            unrelated_payload = json.loads(unrelated.stdout)
        except json.JSONDecodeError as exc:
            raise SageError(
                f"Unrelated retrieval returned invalid JSON: {exc}"
            ) from exc
        if any(
            item.get("identifier") == evidence_id
            for item in unrelated_payload.get("results", [])
        ):
            raise SageError(
                "Published evidence was incorrectly relevant to unrelated retrieval"
            )

        if git(repo, "status", "--porcelain=v1"):
            raise SageError("Self-test repository is not clean")
        print("PASS published evidence is retrievable through canonical policy")
        print("PASS retrieved evidence preserves identity and source provenance")
        print("PASS retrieval dispositions finalize through canonical validation")
        print("PASS unrelated retrieval does not admit published evidence")
        print("\nSAGE publication, reconciliation, and retrieval round-trip self-test: PASS")

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate and publish Kalaxy3 SAGE evidence packages"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    check_p = sub.add_parser("check", help="validate a package without changing Git")
    check_p.add_argument("package", type=Path)
    check_p.add_argument("--repo", help="repository path; defaults to current Git repository")

    publish_p = sub.add_parser("publish", help="validate, commit, and optionally push a package")
    publish_p.add_argument("package", type=Path)
    publish_p.add_argument("--repo", help="repository path; defaults to current Git repository")
    publish_p.add_argument("--push", action="store_true", help="push the completed commits")
    publish_p.add_argument("--remote", default="origin")

    sub.add_parser("self-test", help="run a complete publication test in a temporary Git repository")

    args = parser.parse_args()
    try:
        if args.command == "self-test":
            self_test()
            return 0
        repo = ensure_repo_root(args.repo)
        package = args.package.expanduser().resolve()
        if args.command == "check":
            manifest, warnings = package_check(package, repo)
            print("SAGE package validation: PASS")
            print(f"Evidence ID: {manifest['evidence_id']}")
            print(f"Record:      {manifest['record_path']}")
            for warning in warnings:
                print(warning, file=sys.stderr)
            return 0
        publish(package, repo, push=args.push, remote=args.remote)
        return 0
    except SageError as exc:
        print(f"SAGE publication failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
