#!/usr/bin/env python3
"""Validate and publish a Kalaxy3 SAGE evidence package.

Uses only the Python standard library. The package is generated by an evidence
synthesis tool, while this script is the repository-side enforcement point.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

ALLOWED_STATUSES = {
    "draft",
    "implemented",
    "validated",
    "accepted",
    "superseded",
    "retired",
    "rejected",
}
ALLOWED_RECORD_TYPES = {
    "installation",
    "architecture-decision",
    "change",
    "verification",
    "incident",
    "experiment",
    "benchmark",
    "operations",
    "security",
    "finops",
}
ALLOWED_CATEGORIES = {
    "installation",
    "operations",
    "architecture",
    "decisions",
}
EVIDENCE_ID_RE = re.compile(r"^SAGE-K3-[A-Z0-9-]+-\d{8}-\d{3}$")
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
IMPLEMENTATION_TOKEN = "__SAGE_IMPLEMENTATION_COMMIT__"
PUBLISHED_AT_TOKEN = "__SAGE_PUBLISHED_AT__"

REQUIRED_FRONTMATTER = [
    "evidence_id",
    "schema_version",
    "title",
    "project",
    "record_type",
    "status",
    "classification",
    "created_at",
    "updated_at",
    "valid_as_of",
    "review_due",
    "owner",
    "author",
    "operator",
    "reviewer",
    "environment",
    "system",
    "repository",
    "branch",
    "implementation_commit",
    "record_path",
    "confidence",
    "tags",
    "relationships",
]

# Template headings are intentionally stricter than the standard's broad list.
# Prefix matching permits record-specific suffixes such as
# "Final completion checklist and reviewer acceptance".
REQUIRED_HEADING_PREFIXES = [
    "## Executive summary",
    "## Five Ws and How",
    "## Scope and boundaries",
    "## Final accepted state",
    "## Claims and evidence matrix",
    "## Problem and decision rationale",
    "## Architecture or change description",
    "## Source of truth and implementation lineage",
    "## Prerequisites and assumptions",
    "## Implementation procedure",
    "## Evidence items",
    "## Verification and acceptance criteria",
    "## Idempotency and repeatability",
    "## Security, privacy, and evidence handling",
    "## Reliability, recovery, rollback, and rebuild",
    "## Operational considerations and observability",
    "## Known limitations, evidence gaps, and risks",
    "## Troubleshooting",
    "## Freshness, revalidation, and supersession",
    "## Final completion checklist",
    "## Git review and publication",
    "## Appendices",
]

FATAL_SECRET_PATTERNS = {
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "kubeconfig client key": re.compile(r"(?mi)^\s*client-key-data:\s*[A-Za-z0-9+/=]{40,}\s*$"),
    "bearer token": re.compile(r"(?i)authorization:\s*bearer\s+[A-Za-z0-9._~-]{20,}"),
    "github token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
}
WARNING_SECRET_PATTERNS = {
    "possible password assignment": re.compile(
        r"(?mi)^\s*(?:password|passwd|token|secret)\s*[:=]\s*(?!<|pending|redacted|none|not-applicable)(\S+)"
    ),
}


class SageError(RuntimeError):
    pass


def run(
    args: list[str],
    *,
    cwd: Path,
    check: bool = True,
    capture: bool = True,
) -> subprocess.CompletedProcess[str]:
    proc = subprocess.run(
        args,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.PIPE if capture else None,
    )
    if check and proc.returncode != 0:
        out = (proc.stdout or "").strip()
        err = (proc.stderr or "").strip()
        detail = "\n".join(x for x in [out, err] if x)
        raise SageError(f"Command failed ({proc.returncode}): {' '.join(args)}\n{detail}")
    return proc


def git(repo: Path, *args: str, check: bool = True) -> str:
    return run(["git", *args], cwd=repo, check=check).stdout.strip()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def ensure_repo_root(repo_arg: str | None) -> Path:
    start = Path(repo_arg).expanduser().resolve() if repo_arg else Path.cwd().resolve()
    proc = run(["git", "rev-parse", "--show-toplevel"], cwd=start)
    repo = Path(proc.stdout.strip()).resolve()
    if not (repo / ".git").exists():
        raise SageError(f"Not a normal Git working tree: {repo}")
    return repo


def safe_relpath(value: str, *, field: str) -> PurePosixPath:
    p = PurePosixPath(value)
    if p.is_absolute() or not p.parts or any(part in {"", ".", ".."} for part in p.parts):
        raise SageError(f"Unsafe {field}: {value!r}")
    return p


def zip_entry_is_symlink(info: zipfile.ZipInfo) -> bool:
    mode = info.external_attr >> 16
    return stat.S_ISLNK(mode)


def load_package(package: Path, temp: Path) -> tuple[dict[str, Any], Path]:
    if not package.exists():
        raise SageError(f"Package not found: {package}")
    if package.suffix.lower() != ".zip":
        raise SageError("SAGE packages must be ZIP files")

    with zipfile.ZipFile(package) as zf:
        infos = zf.infolist()
        if len(infos) > 500:
            raise SageError("ZIP contains more than 500 entries")
        total_uncompressed = sum(info.file_size for info in infos)
        if total_uncompressed > 500 * 1024 * 1024:
            raise SageError("ZIP uncompressed payload exceeds 500 MiB")
        names = set()
        for info in infos:
            rel = safe_relpath(info.filename.rstrip("/"), field="ZIP entry") if info.filename.rstrip("/") else None
            if rel is None:
                continue
            if zip_entry_is_symlink(info):
                raise SageError(f"ZIP contains a symbolic link: {info.filename}")
            if info.filename in names:
                raise SageError(f"ZIP contains duplicate entry: {info.filename}")
            names.add(info.filename)
            destination = (temp / Path(*rel.parts)).resolve()
            if temp.resolve() not in destination.parents and destination != temp.resolve():
                raise SageError(f"ZIP path escapes extraction directory: {info.filename}")
        zf.extractall(temp)

    manifest_path = temp / "sage-package.json"
    payload = temp / "payload"
    if not manifest_path.is_file():
        raise SageError("Package is missing sage-package.json")
    if not payload.is_dir():
        raise SageError("Package is missing payload/")

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise SageError(f"Invalid sage-package.json: {exc}") from exc
    if not isinstance(manifest, dict):
        raise SageError("sage-package.json must contain a JSON object")
    return manifest, payload


def require_manifest(manifest: dict[str, Any], key: str, expected_type: type) -> Any:
    if key not in manifest:
        raise SageError(f"Manifest is missing {key!r}")
    value = manifest[key]
    if not isinstance(value, expected_type):
        raise SageError(f"Manifest {key!r} must be {expected_type.__name__}")
    return value


def validate_manifest(manifest: dict[str, Any]) -> None:
    if require_manifest(manifest, "schema_version", str) != "1.0":
        raise SageError("Unsupported package schema_version; expected 1.0")
    if require_manifest(manifest, "repository", str) != "donb4iu/Kalaxy3":
        raise SageError("Manifest repository must be donb4iu/Kalaxy3")
    branch = require_manifest(manifest, "branch", str)
    if not branch:
        raise SageError("Manifest branch cannot be empty")
    evidence_id = require_manifest(manifest, "evidence_id", str)
    if not EVIDENCE_ID_RE.fullmatch(evidence_id):
        raise SageError(f"Invalid evidence_id: {evidence_id}")

    record_path = safe_relpath(require_manifest(manifest, "record_path", str), field="record_path")
    if len(record_path.parts) < 3 or record_path.parts[0] != "markdown":
        raise SageError("record_path must be under markdown/<category>/")
    if record_path.parts[1] not in ALLOWED_CATEGORIES:
        raise SageError(f"Unsupported record category: {record_path.parts[1]}")
    if record_path.suffix != ".md":
        raise SageError("record_path must end in .md")

    checksum_path = safe_relpath(
        require_manifest(manifest, "record_checksum_path", str), field="record_checksum_path"
    )
    if str(checksum_path) != f"{record_path}.sha256":
        raise SageError("record_checksum_path must equal record_path + .sha256")

    artifact_paths = require_manifest(manifest, "artifact_paths", list)
    if not artifact_paths:
        raise SageError("artifact_paths must include at least the publication manifest or terminal evidence")
    for value in artifact_paths:
        if not isinstance(value, str):
            raise SageError("artifact_paths entries must be strings")
        p = safe_relpath(value, field="artifact path")
        expected_prefix = PurePosixPath("markdown", "evidence-artifacts", evidence_id)
        if p.parts[: len(expected_prefix.parts)] != expected_prefix.parts:
            raise SageError(f"Artifact must be under {expected_prefix}: {value}")

    impl_paths = require_manifest(manifest, "implementation_paths", list)
    for value in impl_paths:
        if not isinstance(value, str):
            raise SageError("implementation_paths entries must be strings")
        p = safe_relpath(value, field="implementation path")
        if p.parts[0] == "markdown" and p.parts[1:2] in [("evidence-artifacts",)]:
            raise SageError("Evidence artifact paths cannot be implementation paths")
        if str(p) in {str(record_path), str(checksum_path)}:
            raise SageError("Evidence files cannot be implementation paths")

    mode = require_manifest(manifest, "publication_mode", str)
    if mode not in {"split", "evidence-only"}:
        raise SageError("publication_mode must be split or evidence-only")
    if mode == "split" and not impl_paths:
        raise SageError("split publication requires implementation_paths")
    if mode == "evidence-only" and impl_paths:
        raise SageError("evidence-only publication must not list implementation_paths")

    require_manifest(manifest, "implementation_commit_message", str)
    require_manifest(manifest, "evidence_commit_message", str)
    files = require_manifest(manifest, "files", list)
    if not files:
        raise SageError("Manifest files list cannot be empty")
    seen: set[str] = set()
    for item in files:
        if not isinstance(item, dict):
            raise SageError("Manifest files entries must be objects")
        path = item.get("path")
        digest = item.get("sha256")
        if not isinstance(path, str) or not isinstance(digest, str):
            raise SageError("Each manifest file needs string path and sha256")
        safe_relpath(path, field="manifest file path")
        if path in seen:
            raise SageError(f"Duplicate manifest file path: {path}")
        seen.add(path)
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise SageError(f"Invalid SHA-256 for {path}")

    required_payload = {str(record_path), *artifact_paths}
    if not required_payload.issubset(seen):
        missing = sorted(required_payload - seen)
        raise SageError(f"Manifest files list omits payload files: {missing}")


def verify_payload_hashes(manifest: dict[str, Any], payload: Path) -> None:
    declared: set[str] = set()
    for item in manifest["files"]:
        rel = safe_relpath(item["path"], field="manifest file path")
        path = payload / Path(*rel.parts)
        if not path.is_file():
            raise SageError(f"Declared payload file missing: {rel}")
        actual = sha256_file(path)
        if actual != item["sha256"]:
            raise SageError(f"Payload checksum mismatch for {rel}: expected {item['sha256']}, got {actual}")
        declared.add(str(rel))

    actual_files = {
        p.relative_to(payload).as_posix()
        for p in payload.rglob("*")
        if p.is_file()
    }
    extra = sorted(actual_files - declared)
    missing = sorted(declared - actual_files)
    if extra or missing:
        raise SageError(f"Payload file inventory mismatch; extra={extra}, missing={missing}")


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        raise SageError("Evidence record must start with YAML front matter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise SageError("Evidence record front matter is not terminated")
    block = text[4:end]
    body = text[end + 5 :]
    scalar: dict[str, str] = {}
    for line in block.splitlines():
        if not line or line[0].isspace() or ":" not in line:
            continue
        key, value = line.split(":", 1)
        scalar[key.strip()] = value.strip().strip('"\'')
    return scalar, body


def validate_heading_order(body: str) -> None:
    headings = [line.rstrip() for line in body.splitlines() if line.startswith("## ")]
    pos = -1
    for required in REQUIRED_HEADING_PREFIXES:
        found = None
        for idx in range(pos + 1, len(headings)):
            if headings[idx].startswith(required):
                found = idx
                break
        if found is None:
            raise SageError(f"Evidence record is missing required section: {required}")
        pos = found


def section_text(body: str, heading_prefix: str) -> str:
    lines = body.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith(heading_prefix):
            start = i + 1
            break
    if start is None:
        return ""
    end = len(lines)
    for i in range(start, len(lines)):
        if lines[i].startswith("## "):
            end = i
            break
    return "\n".join(lines[start:end])


def validate_claims_and_evidence(body: str) -> None:
    claim_rows = re.findall(r"(?m)^\|\s*`(CLM-\d{3,})`\s*\|(.+)$", body)
    if not claim_rows:
        raise SageError("Claims and evidence matrix contains no CLM rows")
    evidence_headings = re.findall(r"(?m)^###\s+`(EV-\d{3,})`\s+—", body)
    if not evidence_headings:
        raise SageError("Evidence items section contains no EV headings")
    if len(evidence_headings) != len(set(evidence_headings)):
        raise SageError("Duplicate evidence IDs found")
    available = set(evidence_headings)
    for claim_id, rest in claim_rows:
        refs = set(re.findall(r"EV-\d{3,}", rest))
        if not refs:
            raise SageError(f"{claim_id} has no evidence IDs")
        missing = refs - available
        if missing:
            raise SageError(f"{claim_id} references missing evidence IDs: {sorted(missing)}")
        cells = [c.strip().lower() for c in rest.split("|")]
        if "critical" in cells and not refs:
            raise SageError(f"Critical claim {claim_id} lacks evidence")


def scan_secrets(text: str, path: str) -> list[str]:
    warnings: list[str] = []
    for label, pattern in FATAL_SECRET_PATTERNS.items():
        if pattern.search(text):
            raise SageError(f"Potential {label} found in {path}")
    for label, pattern in WARNING_SECRET_PATTERNS.items():
        if pattern.search(text):
            warnings.append(f"WARNING: {label} found in {path}; review before publication")
    return warnings


def validate_record(
    record_path: Path,
    manifest: dict[str, Any],
    *,
    published: bool,
) -> list[str]:
    text = record_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(text)
    missing = [key for key in REQUIRED_FRONTMATTER if key not in fm]
    if missing:
        raise SageError(f"Missing front-matter fields: {missing}")
    if fm["evidence_id"] != manifest["evidence_id"]:
        raise SageError("Record evidence_id does not match package manifest")
    if fm["schema_version"] != "1.0":
        raise SageError("Record schema_version must be 1.0")
    if fm["project"] != "Kalaxy3" or fm["system"] != "Kalaxy3":
        raise SageError("Record project and system must be Kalaxy3")
    if fm["repository"] != "donb4iu/Kalaxy3":
        raise SageError("Record repository must be donb4iu/Kalaxy3")
    if fm["record_path"] != manifest["record_path"]:
        raise SageError("Record record_path does not match package manifest")
    if fm["branch"] != manifest["branch"]:
        raise SageError("Record branch does not match package manifest")
    if fm["status"] not in ALLOWED_STATUSES:
        raise SageError(f"Invalid lifecycle status: {fm['status']}")
    if fm["record_type"] not in ALLOWED_RECORD_TYPES:
        raise SageError(f"Invalid record_type: {fm['record_type']}")

    impl = fm["implementation_commit"]
    if published:
        if not SHA_RE.fullmatch(impl):
            raise SageError("Published record must contain a 40-character implementation commit SHA")
        if IMPLEMENTATION_TOKEN in text or PUBLISHED_AT_TOKEN in text:
            raise SageError("Published record still contains publication tokens")
    else:
        if manifest["publication_mode"] == "split" and impl != IMPLEMENTATION_TOKEN:
            raise SageError(
                f"Split package record must use implementation_commit: {IMPLEMENTATION_TOKEN}"
            )
        if manifest["publication_mode"] == "evidence-only" and impl not in {
            IMPLEMENTATION_TOKEN,
            "not-applicable",
        } and not SHA_RE.fullmatch(impl):
            raise SageError("Evidence-only record has invalid implementation_commit")

    validate_heading_order(body)
    validate_claims_and_evidence(body)

    five_w = section_text(body, "## Five Ws and How")
    if fm["status"] in {"validated", "accepted"}:
        unchecked = re.findall(r"(?m)^- \[ \] (Who|What|When|Where|Why|How)\b", five_w)
        if unchecked:
            raise SageError(f"Validated/accepted record has incomplete Five-W gate: {unchecked}")
    if fm["status"] == "accepted" and fm["reviewer"].strip().lower() in {"pending", "none", ""}:
        raise SageError("Accepted record requires a named reviewer")

    if fm["status"] in {"validated", "accepted"}:
        checklist = section_text(body, "## Final completion checklist")
        unchecked = re.findall(r"(?m)^- \[ \] (.+)$", checklist)
        if unchecked:
            raise SageError(
                "Validated/accepted record has unchecked final checklist items: "
                + "; ".join(unchecked[:5])
            )

    template_markers = [
        "SAGE-K3-<DOMAIN>",
        "<Concise evidence-record title>",
        "<Atomic, testable claim>",
        "<exact command or source reference>",
    ]
    for marker in template_markers:
        if marker in text:
            raise SageError(f"Unresolved template marker found: {marker}")

    warnings = scan_secrets(text, manifest["record_path"])
    return warnings


def validate_artifacts(payload: Path, manifest: dict[str, Any]) -> list[str]:
    warnings: list[str] = []
    for rel_str in manifest["artifact_paths"]:
        rel = safe_relpath(rel_str, field="artifact path")
        path = payload / Path(*rel.parts)
        if not path.is_file():
            raise SageError(f"Artifact missing from package: {rel}")
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        warnings.extend(scan_secrets(text, str(rel)))
    return warnings


def ensure_repo_contract(repo: Path, manifest: dict[str, Any]) -> None:
    standard = repo / "markdown/standards/kalaxy3-sage-evidence-record-standard.md"
    template = repo / "markdown/templates/sage-evidence-record-template.md"
    if not standard.is_file():
        raise SageError(f"Missing SAGE standard: {standard.relative_to(repo)}")
    if not template.is_file():
        raise SageError(f"Missing SAGE template: {template.relative_to(repo)}")
    current_branch = git(repo, "branch", "--show-current")
    if current_branch != manifest["branch"]:
        raise SageError(f"Current branch is {current_branch!r}; package requires {manifest['branch']!r}")
    remote_url = git(repo, "remote", "get-url", "origin", check=False)
    if remote_url and "donb4iu/Kalaxy3" not in remote_url:
        raise SageError(f"origin does not appear to be donb4iu/Kalaxy3: {remote_url}")


def ensure_clean_index(repo: Path) -> None:
    proc = run(["git", "diff", "--cached", "--quiet"], cwd=repo, check=False)
    if proc.returncode not in {0, 1}:
        raise SageError("Unable to inspect Git index")
    if proc.returncode == 1:
        raise SageError("Git index already contains staged changes; unstage them before publishing")


def fetch_and_require_up_to_date(repo: Path, branch: str, remote: str) -> None:
    git(repo, "fetch", remote, branch)
    upstream = f"{remote}/{branch}"
    local = git(repo, "rev-parse", "HEAD")
    remote_sha = git(repo, "rev-parse", upstream)
    base = git(repo, "merge-base", "HEAD", upstream)
    if local == remote_sha:
        return
    if base == local:
        # Local branch is behind. Rebase before publication while preserving
        # the uncommitted implementation working tree.
        git(repo, "pull", "--rebase", "--autostash", remote, branch)
        return
    if base == remote_sha:
        # Local branch is ahead; publication can continue.
        return
    raise SageError(
        f"Local {branch} and {upstream} have diverged. Resolve divergence before SAGE publication."
    )


def modified_for_paths(repo: Path, paths: Iterable[str]) -> list[str]:
    path_list = list(paths)
    if not path_list:
        return []
    out = git(repo, "status", "--porcelain=v1", "--", *path_list)
    return [line for line in out.splitlines() if line.strip()]


def stage_exact(repo: Path, paths: list[str]) -> None:
    if not paths:
        return
    git(repo, "add", "--", *paths)
    run(["git", "diff", "--cached", "--check"], cwd=repo)
    staged = git(repo, "diff", "--cached", "--name-only").splitlines()
    unexpected = sorted(set(staged) - set(paths))
    missing = sorted(set(paths) - set(staged))
    if unexpected:
        raise SageError(f"Unexpected staged paths: {unexpected}")
    if missing:
        # Existing unchanged paths are not errors, but split mode requires at
        # least one staged implementation change.
        changed = modified_for_paths(repo, missing)
        if changed:
            raise SageError(f"Changed paths were not staged: {missing}")


def commit(repo: Path, message: str) -> str:
    if not message.strip():
        raise SageError("Commit message cannot be empty")
    git(repo, "commit", "-m", message)
    return git(repo, "rev-parse", "HEAD")


def copy_payload(payload: Path, repo: Path, manifest: dict[str, Any]) -> list[str]:
    evidence_paths = [manifest["record_path"], *manifest["artifact_paths"]]
    for rel_str in evidence_paths:
        rel = safe_relpath(rel_str, field="evidence path")
        source = payload / Path(*rel.parts)
        destination = repo / Path(*rel.parts)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    return evidence_paths


def replace_publication_tokens(record: Path, implementation_sha: str) -> None:
    text = record.read_text(encoding="utf-8")
    if IMPLEMENTATION_TOKEN in text:
        text = text.replace(IMPLEMENTATION_TOKEN, implementation_sha)
    elif f"implementation_commit: {implementation_sha}" not in text:
        fm, _ = parse_frontmatter(text)
        if fm.get("implementation_commit") not in {"not-applicable", implementation_sha}:
            raise SageError("Record lacks the implementation commit token")
    published_at = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    text = text.replace(PUBLISHED_AT_TOKEN, published_at)
    record.write_text(text, encoding="utf-8")


def write_record_checksum(repo: Path, manifest: dict[str, Any]) -> str:
    record_rel = manifest["record_path"]
    checksum_rel = manifest["record_checksum_path"]
    digest = sha256_file(repo / record_rel)
    (repo / checksum_rel).write_text(f"{digest}  {record_rel}\n", encoding="utf-8")
    return checksum_rel


def write_publication_manifest(
    repo: Path,
    manifest: dict[str, Any],
    implementation_sha: str,
) -> str:
    evidence_id = manifest["evidence_id"]
    rel = f"markdown/evidence-artifacts/{evidence_id}/publication-manifest.json"
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    published = dict(manifest)
    published["resolved_implementation_commit"] = implementation_sha
    published["published_at"] = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    published["standard_path"] = "markdown/standards/kalaxy3-sage-evidence-record-standard.md"
    published["standard_sha256"] = sha256_file(repo / published["standard_path"])
    published["template_path"] = "markdown/templates/sage-evidence-record-template.md"
    published["template_sha256"] = sha256_file(repo / published["template_path"])
    # Package hashes describe the original package payload. The final record
    # checksum is stored separately after token replacement.
    path.write_text(json.dumps(published, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return rel


def verify_record_checksum(repo: Path, manifest: dict[str, Any]) -> None:
    record_rel = manifest["record_path"]
    checksum_rel = manifest["record_checksum_path"]
    line = (repo / checksum_rel).read_text(encoding="utf-8").strip()
    expected = f"{sha256_file(repo / record_rel)}  {record_rel}"
    if line != expected:
        raise SageError("Final evidence-record checksum verification failed")


def rebase_repair_if_needed(
    repo: Path,
    manifest: dict[str, Any],
    implementation_sha: str,
    remote: str,
) -> tuple[str, str]:
    branch = manifest["branch"]
    git(repo, "fetch", remote, branch)
    upstream = f"{remote}/{branch}"
    proc = run(["git", "merge-base", "--is-ancestor", upstream, "HEAD"], cwd=repo, check=False)
    if proc.returncode == 0:
        return implementation_sha, git(repo, "rev-parse", "HEAD")
    if proc.returncode != 1:
        raise SageError("Unable to compare local branch to upstream")

    mode = manifest["publication_mode"]
    try:
        git(repo, "rebase", upstream)
    except SageError:
        git(repo, "rebase", "--abort", check=False)
        raise
    evidence_sha = git(repo, "rev-parse", "HEAD")
    if mode == "split":
        new_impl = git(repo, "rev-parse", "HEAD~1")
    else:
        new_impl = manifest.get("evidence_only_implementation_commit") or git(repo, "rev-parse", "HEAD~1")

    if new_impl != implementation_sha:
        record = repo / manifest["record_path"]
        text = record.read_text(encoding="utf-8")
        if implementation_sha not in text:
            raise SageError("Rebase changed implementation SHA, but old SHA is not present in evidence record")
        record.write_text(text.replace(implementation_sha, new_impl), encoding="utf-8")
        write_record_checksum(repo, manifest)
        publication_manifest = (
            repo
            / "markdown/evidence-artifacts"
            / manifest["evidence_id"]
            / "publication-manifest.json"
        )
        data = json.loads(publication_manifest.read_text(encoding="utf-8"))
        data["resolved_implementation_commit"] = new_impl
        data["published_at"] = dt.datetime.now().astimezone().isoformat(timespec="seconds")
        publication_manifest.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        evidence_paths = [
            manifest["record_path"],
            manifest["record_checksum_path"],
            *manifest["artifact_paths"],
            publication_manifest.relative_to(repo).as_posix(),
        ]
        git(repo, "add", "--", *sorted(set(evidence_paths)))
        run(["git", "diff", "--cached", "--check"], cwd=repo)
        git(repo, "commit", "--amend", "--no-edit")
        evidence_sha = git(repo, "rev-parse", "HEAD")
        implementation_sha = new_impl
    return implementation_sha, evidence_sha


def package_check(package: Path, repo: Path | None = None) -> tuple[dict[str, Any], list[str]]:
    warnings: list[str] = []
    with tempfile.TemporaryDirectory(prefix="sage-package-") as td:
        temp = Path(td)
        manifest, payload = load_package(package, temp)
        validate_manifest(manifest)
        verify_payload_hashes(manifest, payload)
        record_rel = safe_relpath(manifest["record_path"], field="record_path")
        warnings.extend(validate_record(payload / Path(*record_rel.parts), manifest, published=False))
        warnings.extend(validate_artifacts(payload, manifest))
        if repo is not None:
            ensure_repo_contract(repo, manifest)
    return manifest, warnings


def publish(package: Path, repo: Path, *, push: bool, remote: str) -> None:
    with tempfile.TemporaryDirectory(prefix="sage-package-") as td:
        temp = Path(td)
        manifest, payload = load_package(package, temp)
        validate_manifest(manifest)
        verify_payload_hashes(manifest, payload)
        record_rel = safe_relpath(manifest["record_path"], field="record_path")
        warnings = validate_record(payload / Path(*record_rel.parts), manifest, published=False)
        warnings.extend(validate_artifacts(payload, manifest))
        ensure_repo_contract(repo, manifest)
        ensure_clean_index(repo)
        fetch_and_require_up_to_date(repo, manifest["branch"], remote)

        implementation_paths = list(manifest["implementation_paths"])
        implementation_sha: str
        if manifest["publication_mode"] == "split":
            changed = modified_for_paths(repo, implementation_paths)
            if not changed:
                raise SageError("No implementation changes found for split publication")
            stage_exact(repo, implementation_paths)
            if not git(repo, "diff", "--cached", "--name-only"):
                raise SageError("Implementation staging produced no changes")
            implementation_sha = commit(repo, manifest["implementation_commit_message"])
        else:
            requested = manifest.get("evidence_only_implementation_commit")
            if requested:
                if not isinstance(requested, str) or not SHA_RE.fullmatch(requested):
                    raise SageError("evidence_only_implementation_commit must be a full Git SHA")
                git(repo, "cat-file", "-e", f"{requested}^{{commit}}")
                implementation_sha = requested
            else:
                implementation_sha = git(repo, "rev-parse", "HEAD")

        evidence_paths = copy_payload(payload, repo, manifest)
        record = repo / manifest["record_path"]
        replace_publication_tokens(record, implementation_sha)
        checksum_rel = write_record_checksum(repo, manifest)
        publication_manifest_rel = write_publication_manifest(repo, manifest, implementation_sha)
        evidence_paths.extend([checksum_rel, publication_manifest_rel])
        evidence_paths = sorted(set(evidence_paths))

        # Validate final files after deterministic token replacement.
        warnings.extend(validate_record(record, manifest, published=True))
        verify_record_checksum(repo, manifest)
        run(["git", "diff", "--check"], cwd=repo)

        stage_exact(repo, evidence_paths)
        evidence_sha = commit(repo, manifest["evidence_commit_message"])

        if push:
            implementation_sha, evidence_sha = rebase_repair_if_needed(
                repo,
                manifest,
                implementation_sha,
                remote,
            )
            git(repo, "push", remote, manifest["branch"])

        status = git(repo, "status", "--porcelain=v1")
        if status:
            # Unrelated untracked/modified files are permitted only when they
            # predated publication. Report them prominently instead of claiming
            # a clean tree.
            print("\nPublication completed, but the working tree is not clean:")
            print(status)
        else:
            print("\nPublication completed with a clean working tree.")

        print(f"Evidence ID:           {manifest['evidence_id']}")
        print(f"Implementation commit: {implementation_sha}")
        print(f"Evidence commit:       {evidence_sha}")
        print(f"Record:                {manifest['record_path']}")
        print(f"Checksum:              {manifest['record_checksum_path']}")
        if push:
            print(f"Published to:          {remote}/{manifest['branch']}")
        for warning in sorted(set(warnings)):
            print(warning, file=sys.stderr)


def make_dummy_record(evidence_id: str, record_path: str) -> str:
    headings = "\n\n".join(
        [
            "## Executive summary\n\nValidated dummy process evidence.",
            "## Five Ws and How\n\n| Requirement | Answer |\n|---|---|\n| **Who** | Test |\n| **What** | Test |\n| **When** | Test UTC |\n| **Where** | Test repo |\n| **Why** | Test |\n| **How** | Test |\n\n### Five-W completeness gate\n\n- [x] Who is complete.\n- [x] What is complete.\n- [x] When is complete and includes timezone.\n- [x] Where is complete at both repository and runtime levels.\n- [x] Why includes rationale and tradeoffs.\n- [x] How is reproducible and verifiable.",
            "## Scope and boundaries\n\nTest scope.",
            "## Final accepted state\n\nTest state.",
            "## Claims and evidence matrix\n\n| Claim ID | Claim | Criticality | Evidence IDs | Result | Confidence |\n|---|---|---|---|---|---|\n| `CLM-001` | Test claim | critical | `EV-001` | supported | high |",
            "## Problem and decision rationale\n\nTest rationale.",
            "## Architecture or change description\n\nTest architecture.",
            "## Source of truth and implementation lineage\n\nTest lineage.",
            "## Prerequisites and assumptions\n\nNone.",
            "## Implementation procedure\n\nTest procedure.",
            "## Evidence items\n\n### `EV-001` — Test evidence\n\n| Field | Value |\n|---|---|\n| Classification | `repository-evidence` |\n| Supports or contradicts | `CLM-001` |\n| Collected by | self-test |\n| Collected at | 2026-07-25T00:00:00-05:00 |\n| Execution source | temporary repository |\n| Target | test file |\n| Tool and version | Git |\n| Expected result | pass |\n| Actual result | pass |\n| Confidence | high |\n| Sensitive data | none |\n| Artifact | inline |",
            "## Verification and acceptance criteria\n\nPass.",
            "## Idempotency and repeatability\n\nPass.",
            "## Security, privacy, and evidence handling\n\nNo secrets.",
            "## Reliability, recovery, rollback, and rebuild\n\nRevert commits.",
            "## Operational considerations and observability\n\nGit status.",
            "## Known limitations, evidence gaps, and risks\n\nNone for self-test.",
            "## Troubleshooting\n\nInspect error.",
            "## Freshness, revalidation, and supersession\n\nRevalidate on script change.",
            "## Final completion checklist\n\n- [x] Evidence ID is unique and permanent.\n- [x] Status accurately reflects completeness.\n- [x] Implementation commit is injected by the publisher.\n- [x] Required evidence is present.\n- [x] Secrets are excluded.\n- [x] Revalidation criteria are defined.",
            "## Git review and publication\n\nAutomated.",
            "## Appendices and raw artifacts\n\nTest artifact.",
        ]
    )
    front = f"""---
evidence_id: {evidence_id}
schema_version: "1.0"
title: SAGE publication self-test
project: Kalaxy3
record_type: operations
status: validated
classification: internal
created_at: 2026-07-25T00:00:00-05:00
updated_at: {PUBLISHED_AT_TOKEN}
valid_as_of: 2026-07-25
review_due: event-based
owner: test
author: self-test
operator: self-test
reviewer: pending
environment: test
system: Kalaxy3
cluster: not-applicable
repository: donb4iu/Kalaxy3
branch: main
implementation_commit: {IMPLEMENTATION_TOKEN}
record_path: {record_path}
confidence: high
tags:
  - sage
relationships:
  verifies:
    - self-test
---

# SAGE publication self-test

"""
    return front + headings + "\n"


def self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="sage-self-test-") as td:
        base = Path(td)
        remote = base / "donb4iu" / "Kalaxy3.git"
        remote.parent.mkdir(parents=True)
        repo = base / "repo"
        run(["git", "init", "--bare", str(remote)], cwd=base)
        run(["git", "init", "-b", "main", str(repo)], cwd=base)
        git(repo, "config", "user.name", "SAGE Self Test")
        git(repo, "config", "user.email", "sage-self-test@example.invalid")
        git(repo, "remote", "add", "origin", str(remote))
        (repo / "markdown/standards").mkdir(parents=True)
        (repo / "markdown/templates").mkdir(parents=True)
        (repo / "markdown/standards/kalaxy3-sage-evidence-record-standard.md").write_text(
            "# test standard\n", encoding="utf-8"
        )
        (repo / "markdown/templates/sage-evidence-record-template.md").write_text(
            "# test template\n", encoding="utf-8"
        )
        (repo / "implementation.txt").write_text("before\n", encoding="utf-8")
        git(repo, "add", ".")
        git(repo, "commit", "-m", "Initialize test repository")
        git(repo, "push", "-u", "origin", "main")
        (repo / "implementation.txt").write_text("after\n", encoding="utf-8")

        evidence_id = "SAGE-K3-TEST-20260725-001"
        record_rel = "markdown/operations/sage-publication-self-test.md"
        artifact_rel = f"markdown/evidence-artifacts/{evidence_id}/terminal.md"
        package_dir = base / "package"
        payload = package_dir / "payload"
        (payload / Path(record_rel).parent).mkdir(parents=True)
        (payload / Path(artifact_rel).parent).mkdir(parents=True)
        (payload / record_rel).write_text(make_dummy_record(evidence_id, record_rel), encoding="utf-8")
        (payload / artifact_rel).write_text("# self-test artifact\n", encoding="utf-8")
        files = []
        for rel in [record_rel, artifact_rel]:
            files.append({"path": rel, "sha256": sha256_file(payload / rel)})
        manifest = {
            "schema_version": "1.0",
            "repository": "donb4iu/Kalaxy3",
            "branch": "main",
            "evidence_id": evidence_id,
            "record_path": record_rel,
            "record_checksum_path": record_rel + ".sha256",
            "artifact_paths": [artifact_rel],
            "implementation_paths": ["implementation.txt"],
            "publication_mode": "split",
            "implementation_commit_message": "Apply self-test implementation",
            "evidence_commit_message": "Add self-test SAGE evidence",
            "files": files,
        }
        package_dir.mkdir(exist_ok=True)
        (package_dir / "sage-package.json").write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
        )
        package_zip = base / "self-test.zip"
        with zipfile.ZipFile(package_zip, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in package_dir.rglob("*"):
                if path.is_file():
                    zf.write(path, path.relative_to(package_dir).as_posix())
        publish(package_zip, repo, push=True, remote="origin")
        log = git(repo, "log", "--oneline", "-3")
        if "Add self-test SAGE evidence" not in log or "Apply self-test implementation" not in log:
            raise SageError("Self-test commits were not created")
        if git(repo, "status", "--porcelain=v1"):
            raise SageError("Self-test repository is not clean")
        print("\nSAGE publication self-test: PASS")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate and publish Kalaxy3 SAGE evidence packages"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    check_p = sub.add_parser("check", help="validate a package without changing Git")
    check_p.add_argument("package", type=Path)
    check_p.add_argument("--repo", help="repository path; defaults to current Git repository")

    publish_p = sub.add_parser("publish", help="validate, commit, and optionally push a package")
    publish_p.add_argument("package", type=Path)
    publish_p.add_argument("--repo", help="repository path; defaults to current Git repository")
    publish_p.add_argument("--push", action="store_true", help="push the completed commits")
    publish_p.add_argument("--remote", default="origin")

    sub.add_parser("self-test", help="run a complete publication test in a temporary Git repository")

    args = parser.parse_args()
    try:
        if args.command == "self-test":
            self_test()
            return 0
        repo = ensure_repo_root(args.repo)
        package = args.package.expanduser().resolve()
        if args.command == "check":
            manifest, warnings = package_check(package, repo)
            print("SAGE package validation: PASS")
            print(f"Evidence ID: {manifest['evidence_id']}")
            print(f"Record:      {manifest['record_path']}")
            for warning in warnings:
                print(warning, file=sys.stderr)
            return 0
        publish(package, repo, push=args.push, remote=args.remote)
        return 0
    except SageError as exc:
        print(f"SAGE publication failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
